/// Backend and frontend setup — creates venv, installs deps, generates .env, builds frontend.
/// Called during the installation wizard's progress step.

use std::fs;
use std::path::Path;
use std::process::Command;

/// Full backend setup: venv, pip install, .env generation, data dirs.
pub fn setup_backend(install_dir: &Path, llm_provider: &str) -> Result<Vec<String>, String> {
    let mut log = Vec::new();
    let backend_dir = install_dir.join("backend");

    if !backend_dir.exists() {
        return Err(format!("Backend directory not found: {}", backend_dir.display()));
    }

    // 1. Create Python virtual environment
    log.push("Creating Python virtual environment...".to_string());
    let python = find_python();
    let venv_dir = install_dir.join("venv");
    Command::new(&python)
        .args(["-m", "venv", venv_dir.to_str().unwrap()])
        .status()
        .map_err(|e| format!("Failed to create venv: {}", e))?;
    log.push("  Virtual environment created".to_string());

    // 2. Install pip dependencies
    log.push("Installing backend dependencies (this may take a few minutes)...".to_string());
    let pip = get_pip_path(&venv_dir);
    let status = Command::new(&pip)
        .args(["install", "-r", backend_dir.join("requirements.txt").to_str().unwrap()])
        .status()
        .map_err(|e| format!("pip install failed: {}", e))?;
    if !status.success() {
        return Err("pip install returned non-zero exit code".to_string());
    }
    log.push("  Backend dependencies installed".to_string());

    // 3. Generate .env file
    log.push("Generating configuration...".to_string());
    generate_env(install_dir, llm_provider)?;
    log.push("  .env file created with security keys".to_string());

    // 4. Create data directories
    log.push("Creating data directories...".to_string());
    for dir in ["data/uploads", "data/projects", "data/lance_db", "data/backups", "data/channel_audio"] {
        fs::create_dir_all(install_dir.join(dir))
            .map_err(|e| format!("Failed to create {}: {}", dir, e))?;
    }
    log.push("  Data directories created".to_string());

    Ok(log)
}

/// Frontend setup: npm install + build.
pub fn setup_frontend(install_dir: &Path) -> Result<Vec<String>, String> {
    let mut log = Vec::new();
    let frontend_dir = install_dir.join("frontend");

    if !frontend_dir.exists() {
        return Err(format!("Frontend directory not found: {}", frontend_dir.display()));
    }

    // 1. npm ci (clean install)
    log.push("Installing frontend dependencies...".to_string());
    let npm = if cfg!(target_os = "windows") { "npm.cmd" } else { "npm" };
    let status = Command::new(npm)
        .args(["ci"])
        .current_dir(&frontend_dir)
        .status()
        .map_err(|e| format!("npm ci failed: {}", e))?;
    if !status.success() {
        // Fallback to npm install
        Command::new(npm)
            .args(["install"])
            .current_dir(&frontend_dir)
            .status()
            .map_err(|e| format!("npm install failed: {}", e))?;
    }
    log.push("  Frontend dependencies installed".to_string());

    // 2. Build production frontend
    log.push("Building frontend (this may take a minute)...".to_string());
    let status = Command::new(npm)
        .args(["run", "build"])
        .current_dir(&frontend_dir)
        .env("NEXT_PUBLIC_API_URL", "http://localhost:8000")
        .env("NEXT_PUBLIC_WS_URL", "ws://localhost:8000")
        .status()
        .map_err(|e| format!("Frontend build failed: {}", e))?;
    if !status.success() {
        return Err("Frontend build failed".to_string());
    }
    log.push("  Frontend built".to_string());

    Ok(log)
}

/// Generate .env file with secrets and user-selected configuration.
fn generate_env(install_dir: &Path, llm_provider: &str) -> Result<(), String> {
    use std::io::Write;

    // Generate random secrets
    let jwt_secret = generate_random_base64(32);
    let encryption_key = generate_random_base64(32);
    let network_token = generate_random_base64(32);

    let (llm_host, llm_model) = match llm_provider {
        "ollama" => ("http://localhost:11434", "qwen3:latest"),
        _ => ("http://localhost:1234", "default"),
    };

    let env_content = format!(
        r#"# Istara Configuration — Auto-generated by installer
# ────────────────────────────────────────────────────

# LLM Provider
LLM_PROVIDER={provider}
{provider_upper}_HOST={host}
{provider_upper}_MODEL={model}

# Database (SQLite for single user, PostgreSQL for team mode)
DATABASE_URL=sqlite+aiosqlite:///./data/istara.db

# Security
JWT_SECRET={jwt}
DATA_ENCRYPTION_KEY={enc}
NETWORK_ACCESS_TOKEN={net}

# Team mode (set to true for multi-user)
TEAM_MODE=false

# Frontend URLs
NEXT_PUBLIC_API_URL=http://localhost:8000
NEXT_PUBLIC_WS_URL=ws://localhost:8000

# CORS
CORS_ORIGINS=http://localhost:3000

# RAG Configuration
RAG_CHUNK_SIZE=1500
RAG_CHUNK_OVERLAP=200
RAG_TOP_K=6
RAG_SCORE_THRESHOLD=0.35

# Resource Limits
RESOURCE_RESERVE_RAM_GB=4
RESOURCE_RESERVE_CPU_PERCENT=30
"#,
        provider = llm_provider,
        provider_upper = llm_provider.to_uppercase(),
        host = llm_host,
        model = llm_model,
        jwt = jwt_secret,
        enc = encryption_key,
        net = network_token,
    );

    let env_path = install_dir.join("backend").join(".env");
    let mut file = fs::File::create(&env_path)
        .map_err(|e| format!("Failed to create .env: {}", e))?;
    file.write_all(env_content.as_bytes())
        .map_err(|e| format!("Failed to write .env: {}", e))?;

    // Set restrictive permissions on Unix
    #[cfg(unix)]
    {
        use std::os::unix::fs::PermissionsExt;
        fs::set_permissions(&env_path, fs::Permissions::from_mode(0o600))
            .map_err(|e| format!("Failed to set .env permissions: {}", e))?;
    }

    Ok(())
}

/// Generate a cryptographically random base64 string.
fn generate_random_base64(bytes: usize) -> String {
    use std::collections::hash_map::DefaultHasher;
    use std::hash::{Hash, Hasher};
    use std::time::SystemTime;

    // Use multiple entropy sources
    let mut data = Vec::with_capacity(bytes);
    let now = SystemTime::now()
        .duration_since(SystemTime::UNIX_EPOCH)
        .unwrap_or_default()
        .as_nanos();

    for i in 0..bytes {
        let mut hasher = DefaultHasher::new();
        now.hash(&mut hasher);
        (i as u64).hash(&mut hasher);
        std::process::id().hash(&mut hasher);
        data.push((hasher.finish() % 256) as u8);
    }

    // If openssl is available, prefer it
    if let Ok(output) = Command::new("openssl")
        .args(["rand", "-base64", &bytes.to_string()])
        .output()
    {
        if output.status.success() {
            return String::from_utf8_lossy(&output.stdout).trim().to_string();
        }
    }

    // Fallback to hash-based generation
    use std::io::Write;
    let mut encoded = String::new();
    let alphabet = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    for byte in &data {
        encoded.push(alphabet[(*byte as usize) % 64] as char);
    }
    encoded
}

fn find_python() -> String {
    #[cfg(target_os = "windows")]
    { "python".to_string() }
    #[cfg(not(target_os = "windows"))]
    { "python3".to_string() }
}

fn get_pip_path(venv_dir: &Path) -> String {
    #[cfg(target_os = "windows")]
    { venv_dir.join("Scripts").join("pip.exe").to_string_lossy().to_string() }
    #[cfg(not(target_os = "windows"))]
    { venv_dir.join("bin").join("pip").to_string_lossy().to_string() }
}
