"""Conformance tests for the pi-ai catalog projection and the capability
authority boundary (build-stream 2026-09-08-pi-capability-inheritance, waves
W1/W2/W4).

The projection ``backend/app/core/pi_runtime/data/pi_models_catalog.json`` is
generated by ``pi-runtime/scripts/emit-catalog.mjs`` (the only maintenance-time
importer of the pi-ai registry outside the worker). These tests make drift
unmergeable:

- round-trip: regenerating must reproduce the committed file byte-for-byte
  (``emitted_at`` masked) — a pi bump without regeneration fails (AC-5);
- provenance: the committed ``__provenance.pi_ai_version`` must equal the
  installed pi-ai pin (``EXPECTED_PINS``);
- authority equivalence: for every registry model, the projected capability
  fields must equal what the worker resolver computes from the live registry
  (DEC-M1: two read paths, one derivation, machine-checked).

Missing node/node_modules yields a TYPED ``not_runnable`` outcome — never a
silent skip.
"""

from __future__ import annotations

import json
import shutil
import subprocess
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parents[2]
EMITTER = REPO_ROOT / "pi-runtime" / "scripts" / "emit-catalog.mjs"
CATALOG_PATH = REPO_ROOT / "backend" / "app" / "core" / "pi_runtime" / "data" / "pi_models_catalog.json"
CUSTOM_PROVIDERS_DIR = REPO_ROOT / "backend" / "app" / "core" / "pi_runtime" / "data" / "custom_providers"
GENERATOR = REPO_ROOT / "scripts" / "generate_pi_catalog.py"
DUMP_SCRIPT = REPO_ROOT / "pi-runtime" / "scripts" / "dump-resolved-capabilities.mjs"
PIN_SOURCE = REPO_ROOT / "tests" / "pi_migration" / "test_version_provenance.py"


def _expected_pin(package: str) -> str:
    """Read the approved pin from the version-provenance source of truth."""
    text = PIN_SOURCE.read_text(encoding="utf-8")
    marker = f'"{package}":'
    index = text.index(marker)
    _, value = text[index + len(marker):].split('"', 1)
    return value[: value.index('"')]


def _not_runnable(reason: str):
    pytest.skip(f"not_runnable: {reason}")


def _node_env_ready() -> bool:
    return (
        shutil.which("node") is not None
        and (REPO_ROOT / "pi-runtime" / "node_modules" / "@earendil-works" / "pi-ai").exists()
        and DUMP_SCRIPT.exists()
    )


def _catalog() -> dict:
    if not CATALOG_PATH.exists():
        _not_runnable(f"committed catalog missing: {CATALOG_PATH}")
    return json.loads(CATALOG_PATH.read_text(encoding="utf-8"))


def _providers_and_models(catalog: dict) -> dict[str, list[dict]]:
    return {k: v for k, v in catalog.items() if not k.startswith("__")}


def test_round_trip_regeneration_is_byte_identical():
    """`generate_pi_catalog.py --check` must be a no-op on a clean tree (AC-5)."""
    if shutil.which("node") is None:
        _not_runnable("node executable not on PATH")
    if not (REPO_ROOT / "pi-runtime" / "node_modules" / "@earendil-works" / "pi-ai").exists():
        _not_runnable("pi-runtime/node_modules/@earendil-works/pi-ai not installed")
    result = subprocess.run(
        ["python3", str(GENERATOR), "--check"],
        cwd=str(REPO_ROOT),
        capture_output=True,
        text=True,
        timeout=300,
    )
    assert result.returncode == 0, (
        "committed catalog is not byte-identical to the projection of the "
        f"installed pi-ai pin (drift or formatting change):\n{result.stdout}\n{result.stderr}"
    )


def test_provenance_pi_ai_version_equals_approved_pin():
    """__provenance.pi_ai_version must equal the approved EXPECTED_PINS value."""
    provenance = _catalog().get("__provenance")
    assert isinstance(provenance, dict), "projection carries no __provenance header"
    expected = _expected_pin("@earendil-works/pi-ai")
    assert provenance.get("pi_ai_version") == expected, (
        f"projection was emitted for pi-ai {provenance.get('pi_ai_version')} but the "
        f"approved pin is {expected} — regenerate the catalog after a bump"
    )
    # The governed overlays and the registry must be recorded, never implied.
    assert provenance.get("governed_custom_providers") == ["dashscope"]
    assert isinstance(provenance.get("model_field_set_hash"), str)
    assert len(provenance.get("emitter_sha256") or "") == 64


def test_governed_overlay_preserved_across_projection():
    """The dashscope overlay file is hand-owned: the projection must match it
    verbatim and the emitter must never delete or rewrite governed records."""
    overlay_path = CUSTOM_PROVIDERS_DIR / "dashscope.json"
    assert overlay_path.exists(), "governed dashscope overlay is missing"
    overlay = json.loads(overlay_path.read_text(encoding="utf-8"))
    assert overlay.get("__overlay_provenance", {}).get("wire_fixtures"), (
        "a governed overlay without a wire fixture reference is ungoverned"
    )
    projected = {m["id"]: m for m in _providers_and_models(_catalog())["dashscope"]}
    for model in overlay["dashscope"]:
        assert projected.get(model["id"]) == model, (
            f"governed overlay record drifted in the projection: {model['id']}"
        )


def test_projection_registry_parity_no_upstream_deletion():
    """Every registry provider/model must appear exactly once in the projection
    (counts are not the oracle — but a missing record can never pass)."""
    if not _node_env_ready():
        _not_runnable("node or the installed pi-ai package is unavailable")
    dump = json.loads(
        subprocess.run(
            ["node", str(DUMP_SCRIPT), "--mode", "inventory"],
            cwd=str(REPO_ROOT / "pi-runtime"),
            capture_output=True,
            text=True,
            check=True,
            timeout=300,
        ).stdout
    )
    projected = _providers_and_models(_catalog())
    for provider, model_ids in dump["inventory"].items():
        assert provider in projected, f"registry provider {provider} missing from the projection"
        projected_ids = [m["id"] for m in projected[provider]]
        assert len(projected_ids) == len(set(projected_ids)), f"duplicate model ids under {provider}"
        missing = sorted(set(model_ids) - set(projected_ids))
        assert not missing, f"upstream models deleted from the projection: {provider}: {missing[:8]}"


def test_authority_equivalence_projection_matches_worker_resolver():
    """For every registry model the projected capability fields equal what the
    worker resolver computes from the live registry (W4.1 / DEC-M1)."""
    if not _node_env_ready():
        _not_runnable("node or the installed pi-ai package is unavailable")
    dump = json.loads(
        subprocess.run(
            ["node", str(DUMP_SCRIPT), "--mode", "resolved"],
            cwd=str(REPO_ROOT / "pi-runtime"),
            capture_output=True,
            text=True,
            check=True,
            timeout=300,
        ).stdout
    )
    projected = _providers_and_models(_catalog())
    compared = 0
    for entry in dump["resolved"]:
        models = {m["id"]: m for m in projected[entry["pi_provider"]]}
        model = models[entry["model"]]
        assert model["reasoning"] == entry["reasoning"], f"reasoning drift: {entry['pi_provider']}/{entry['model']}"
        assert model["thinkingLevels"] == entry["supported_pi_levels"], (
            f"menu drift: {entry['pi_provider']}/{entry['model']} — "
            "the projected menu must be getSupportedThinkingLevels(record) (DEC-M2)"
        )
        assert model["thinkingLevelMap"] == entry["thinking_level_map"], (
            f"map drift: {entry['pi_provider']}/{entry['model']}"
        )
        projected_compat = model["compat"]
        resolver_compat = entry["compat"]
        if entry["url_default_supports_developer_role"]:
            # The tier-5 URL default (developer role) is a documented additive
            # override on top of the tier-4 record: it only ADDS the field the
            # record did not name — including when the record carries no compat
            # object at all (see provider.mjs isCustomOpenAICompat).
            base = dict(projected_compat) if projected_compat else {}
            assert "supportsDeveloperRole" not in base, (
                f"URL default applied over a record that names the field: {entry['pi_provider']}/{entry['model']}"
            )
            assert resolver_compat == {**base, "supportsDeveloperRole": False}, (
                f"compat drift beyond the URL default: {entry['pi_provider']}/{entry['model']}"
            )
        else:
            assert projected_compat == resolver_compat, (
                f"compat drift: {entry['pi_provider']}/{entry['model']}"
            )
        compared += 1
    assert compared >= 1000, f"equivalence walked only {compared} models — dump truncated?"
