NUGGET_BANK = [
    ("I couldn't find the export button anywhere", 'Interview_P01', ['discoverability', 'navigation']),
    ('the dashboard feels overwhelming with all these charts', 'Interview_P02', ['visual-density', 'analytics']),
    ('I just want to see my tasks for today, nothing else', 'Interview_P03', ['prioritization', 'workflow']),
    ('every time I click save it takes me to a different page', 'Interview_P04', ['flow-break', 'navigation']),
    ("I didn't realize there was a search function until someone showed me", 'Interview_P05', ['discoverability', 'search']),
    ('the mobile version is basically unusable for editing', 'Interview_P06', ['mobile', 'editing']),
    ("I keep losing my work because there's no autosave", 'Interview_P07', ['reliability', 'autosave']),
    ('the onboarding tutorial was way too long and I skipped it', 'Interview_P08', ['onboarding', 'learning']),
    ('I wish I could customize which notifications I receive', 'Interview_P09', ['notifications', 'control']),
    ('the color coding helps me prioritize but the labels are confusing', 'Interview_P10', ['labels', 'prioritization']),
    ('permissions are confusing; I accidentally shared confidential data', 'Interview_P11', ['security', 'permissions']),
    ('the integration with Slack is the only reason we stayed', 'Interview_P12', ['integration', 'retention']),
    ('I need project timelines at a glance, not buried in menus', 'Interview_P13', ['timeline', 'information-architecture']),
    ("the error messages don't tell me what I did wrong", 'Interview_P14', ['errors', 'recovery']),
    ('the progress bar during upload reduced my anxiety significantly', 'Interview_P15', ['feedback', 'trust']),
    ("I can't reconcile my Stripe payouts with our accounting software without manual CSV imports", 'FINTECH_STRIPE_admin_412', ['integration-complexity', 'workflow-friction']),
    ('The patient portal crashes when I try to upload lab results larger than 5MB', 'HEALTHCARE_Epic_patient_891', ['performance-latency', 'file-handling']),
    ('I have to manually copy-paste inventory counts between the warehouse tablet and SAP', 'HEAVY_IND_Siemens_field_worker_203', ['integration-complexity', 'data-export-limitations']),
    ('The AI triage suggestions sometimes contradict our hospital compliance guidelines', 'HEALTHCARE_Cerner_compliance_officer_567', ['trust-risk', 'ai-reliability']),
    ("I can't find the refund button because it's hidden under 'Account Settings > Billing History'", 'ECOM_AMAZON_end_user_104', ['discoverability', 'navigation']),
    ("The mobile app for tracking my Apple Watch workouts doesn't sync with Strava", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_321', ['cross-platform-sync-issues', 'mobile-parity']),
    ("I don't trust the investment recommendations because they sometimes contradict our fiduciary policy", 'INVEST_Fidelity_manager_789', ['trust-risk', 'pricing-transparency']),
    ('The delivery driver app shows outdated traffic data, causing missed time windows', 'DELIVERY_DoorDash_field_worker_456', ['performance-latency', 'offline-capability']),
    ('I have to manually approve every vendor invoice because the approval workflow is too rigid', 'B2B_Salesforce_procurement_612', ['role-permission-confusion', 'workflow-friction']),
    ('The B2Gov tax portal times out during peak filing season and loses my draft', 'B2GOV_IRS_end_user_901', ['reliability', 'state-persistence']),
    ('The gaming matchmaking system pairs me with players 30 levels above mine', 'GAMING_Epic_Games_end_user_234', ['trust-risk', 'performance-latency']),
    ("The automotive telematics dashboard doesn't show real-time fuel consumption on mobile", 'AUTOMOTIVE_Tesla_manager_567', ['mobile-desktop-parity', 'analytics']),
    ("The retail inventory system shows stock as available when it's actually in transit", 'RETAIL_Walmart_admin_890', ['data-export-limitations', 'reliability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_Clio_developer_123', ['search', 'semantic-matching']),
    ('The energy utility metering app drains my battery in 2 hours', 'ENERGY_Tesla_Powerwall_end_user_456', ['performance-latency', 'mobile-parity']),
    ('The travel booking platform shows different prices for the same room depending on device', 'TRAVEL_Airbnb_end_user_789', ['pricing-transparency', 'mobile-desktop-parity']),
    ("The real estate listing tool doesn't allow offline access when I'm touring properties in rural areas", 'REAL_ESTATE_Zillow_field_worker_012', ['offline-capability', 'workflow-friction']),
    ('The media subscription platform charges me twice when I switch payment methods mid-cycle', 'MEDIA_Spotify_end_user_345', ['pricing-transparency', 'trust-risk']),
    ("The EdTech learning platform doesn't adapt to my pace, causing frustration and drop-off", 'EDU_Coursera_end_user_678', ['onboarding-cognitive-load', 'workflow-friction']),
    ('The B2B SaaS platform requires 5 separate logins for our team to access all modules', 'IT_ENTERPRISE_ServiceNow_manager_901', ['integration-complexity', 'role-permission-confusion']),
    ('The healthcare claims processing system rejects valid codes because the taxonomy is outdated', 'HEALTHCARE_Cerner_compliance_officer_234', ['errors', 'compliance']),
    ('The fintech crypto wallet shows incorrect gas fees during network congestion', 'FINTECH_Coinbase_end_user_567', ['performance-latency', 'trust-risk']),
    ('The heavy machinery control panel has no tactile feedback, causing operator errors', 'HEAVY_IND_Caterpillar_field_worker_890', ['accessibility-barrier', 'workflow-friction']),
    ('The automotive OTA update process takes 3 hours and bricks the infotainment system', 'AUTOMOTIVE_Ford_manager_123', ['reliability', 'state-persistence']),
    ('The consumer electronics smart home app requires constant Wi-Fi, failing in basements', 'CONSUMER_ELECTRONICS_Samsung_end_user_456', ['offline-capability', 'mobile-parity']),
    ('The B2Gov public transit app shows inaccurate arrival times, causing missed connections', 'B2GOV_City_of_NYC_Services_end_user_789', ['performance-latency', 'trust-risk']),
    ("The retail loyalty program doesn't track cross-channel purchases, frustrating repeat buyers", 'RETAIL_Target_end_user_012', ['data-export-limitations', 'workflow-friction']),
    ('The legal document automation tool generates non-compliant clauses for international contracts', 'LEGAL_LexisNexis_developer_345', ['errors', 'compliance']),
    ('The energy grid management dashboard lacks real-time load balancing alerts', 'ENERGY_Duke_Energy_manager_678', ['notifications', 'performance-latency']),
    ("The travel airline app doesn't allow seat changes after check-in, causing gate delays", 'TRAVEL_Delta_end_user_901', ['discoverability', 'workflow-friction']),
    ('The real estate mortgage calculator uses outdated interest rates, misleading borrowers', 'REAL_ESTATE_Redfin_end_user_234', ['trust-risk', 'pricing-transparency']),
    ("The media podcast hosting platform doesn't support multi-language transcripts", 'MEDIA_Audible_manager_567', ['accessibility-barrier', 'integration-complexity']),
    ('The EdTech classroom management tool crashes when 30 students join simultaneously', 'EDU_Duolingo_developer_890', ['performance-latency', 'reliability']),
    ('The B2B HR platform requires manual employee onboarding for every new hire', 'IT_ENTERPRISE_SAP_admin_123', ['onboarding-cognitive-load', 'workflow-friction']),
    ('The healthcare telehealth app drops video calls when switching between Wi-Fi and cellular', 'HEALTHCARE_Teladoc_patient_456', ['performance-latency', 'mobile-parity']),
    ('The fintech lending platform rejects applications due to outdated credit scoring models', 'FINTECH_Revolut_manager_789', ['trust-risk', 'compliance']),
    ('The heavy industry safety monitoring system sends duplicate alerts, causing alert fatigue', 'HEAVY_IND_GE_manager_012', ['notification-fatigue', 'workflow-friction']),
    ('The automotive EV charging app shows unavailable chargers that are actually offline', 'AUTOMOTIVE_Rivian_end_user_345', ['reliability', 'trust-risk']),
    ("The consumer electronics fitness tracker doesn't sync with Apple Health on iOS 17", 'CONSUMER_ELECTRONICS_Fitbit_end_user_678', ['cross-platform-sync-issues', 'mobile-parity']),
    ('The B2Gov social services portal requires paper forms for initial applications', 'B2GOV_VA_end_user_901', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail supply chain dashboard doesn't show supplier lead times, causing stockouts", 'RETAIL_Procter_Gamble_manager_234', ['timeline', 'information-architecture']),
    ('The legal e-discovery tool takes 12 hours to index a single case file', 'LEGAL_Ironclad_developer_567', ['performance-latency', 'workflow-friction']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Vestas_manager_890', ['analytics', 'trust-risk']),
    ("The travel hotel booking platform shows rooms as available when they're under maintenance", 'TRAVEL_Marriott_end_user_123', ['reliability', 'trust-risk']),
    ('The real estate property tax calculator uses county-level averages, not parcel-specific data', 'REAL_ESTATE_Compass_end_user_456', ['pricing-transparency', 'errors']),
    ('The media streaming service buffers excessively on 5G networks despite high bandwidth', 'MEDIA_NYT_end_user_789', ['performance-latency', 'mobile-parity']),
    ("The EdTech student progress tracker doesn't show skill mastery gaps, causing redundant assignments", 'EDU_Coursera_manager_012', ['analytics', 'workflow-friction']),
    ('The B2B marketing platform requires manual audience segmentation for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_345', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare prescription refill system doesn't check for drug interactions automatically", 'HEALTHCARE_Epic_patient_678', ['trust-risk', 'errors']),
    ('The fintech peer-to-peer payment app shows incorrect exchange rates for international transfers', 'FINTECH_Plaid_end_user_901', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry crane control interface has no emergency stop confirmation, risking safety', 'HEAVY_IND_Schneider_Electric_field_worker_234', ['accessibility-barrier', 'security']),
    ('The automotive infotainment system requires a software update to recognize new USB-C accessories', 'AUTOMOTIVE_Hyundai_end_user_567', ['discoverability', 'integration-complexity']),
    ("The consumer electronics smart thermostat app doesn't work without a hub, increasing friction", 'CONSUMER_ELECTRONICS_Dyson_end_user_890', ['integration-complexity', 'onboarding-cognitive-load']),
    ('The B2Gov voter registration portal times out during peak hours, losing applications', 'B2GOV_DMV_end_user_123', ['reliability', 'state-persistence']),
    ('The retail POS system crashes during holiday sales, causing checkout queues', 'RETAIL_Walmart_manager_456', ['performance-latency', 'reliability']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Thomson_Reuters_developer_789', ['workflow-friction', 'accessibility-barrier']),
    ("The energy utility billing app doesn't show usage breakdowns by appliance, reducing engagement", 'ENERGY_Enphase_end_user_012', ['analytics', 'discoverability']),
    ('The travel car rental platform shows different insurance costs depending on browser cookies', 'TRAVEL_Expedia_end_user_345', ['pricing-transparency', 'trust-risk']),
    ('The real estate virtual tour feature lags on mobile, causing users to abandon listings', 'REAL_ESTATE_Opendoor_end_user_678', ['performance-latency', 'mobile-parity']),
    ("The media audiobook platform doesn't support background play on iOS, breaking user habits", 'MEDIA_Audible_end_user_901', ['mobile-desktop-parity', 'workflow-friction']),
    ("The EdTech parent portal doesn't show teacher comments, reducing home-school alignment", 'EDU_Duolingo_manager_234', ['discoverability', 'workflow-friction']),
    ('The B2B ITSM platform requires manual ticket routing for cross-departmental issues', 'IT_ENTERPRISE_ServiceNow_manager_567', ['workflow-friction', 'role-permission-confusion']),
    ("The healthcare patient scheduling app doesn't show provider availability in real-time", 'HEALTHCARE_Cerner_patient_890', ['discoverability', 'performance-latency']),
    ('The fintech investment platform shows historical returns without risk-adjusted metrics', 'FINTECH_Fidelity_manager_123', ['analytics', 'trust-risk']),
    ('The heavy industry predictive maintenance system sends false positives, causing unnecessary downtime', 'HEAVY_IND_Boeing_manager_456', ['notification-fatigue', 'trust-risk']),
    ('The automotive keyless entry system fails in cold weather, locking owners out', 'AUTOMOTIVE_Tesla_end_user_789', ['reliability', 'accessibility-barrier']),
    ('The consumer electronics smart speaker app requires constant microphone permissions, raising privacy concerns', 'CONSUMER_ELECTRONICS_Garmin_end_user_012', ['privacy-data-sensitivity', 'discoverability']),
    ('The B2Gov public records portal requires JavaScript, excluding legacy browser users', 'B2GOV_CDC_end_user_345', ['accessibility-barrier', 'mobile-desktop-parity']),
    ("The retail inventory management system doesn't show low-stock alerts until items are sold out", 'RETAIL_Target_manager_678', ['notifications', 'workflow-friction']),
    ("The legal case management tool doesn't support version control, causing document conflicts", 'LEGAL_Clio_manager_901', ['state-persistence', 'workflow-friction']),
    ("The energy grid forecasting model doesn't account for extreme weather events, causing blackouts", 'ENERGY_NextEra_manager_234', ['trust-risk', 'performance-latency']),
    ('The travel flight tracking app shows inaccurate gate changes, causing missed connections', 'TRAVEL_Delta_end_user_567', ['reliability', 'trust-risk']),
    ('The real estate mortgage pre-approval tool uses outdated debt-to-income ratios', 'REAL_ESTATE_Zillow_end_user_890', ['errors', 'pricing-transparency']),
    ('The media news app shows duplicate articles from the same source, reducing content quality', 'MEDIA_NYT_end_user_123', ['workflow-friction', 'discoverability']),
    ('The EdTech exam proctoring system flags legitimate behavior as cheating, causing student distress', 'EDU_Coursera_manager_456', ['trust-risk', 'accessibility-barrier']),
    ('The B2B CRM platform requires manual data entry for every client interaction', 'IT_ENTERPRISE_Salesforce_manager_789', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient-reported outcomes via mobile", 'HEALTHCARE_Pfizer_manager_012', ['mobile-parity', 'workflow-friction']),
    ('The fintech insurance platform shows premiums without explaining coverage gaps', 'FINTECH_Revolut_end_user_345', ['pricing-transparency', 'discoverability']),
    ('The heavy industry drone inspection system fails in high winds, delaying safety checks', 'HEAVY_IND_Caterpillar_field_worker_678', ['reliability', 'performance-latency']),
    ('The automotive connected car app requires a monthly subscription for basic navigation updates', 'AUTOMOTIVE_BMW_end_user_901', ['pricing-transparency', 'trust-risk']),
    ("The consumer electronics smart lock app doesn't work with standard Android keychains", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_234', ['cross-platform-sync-issues', 'integration-complexity']),
    ('The B2Gov public health dashboard shows outdated case counts, reducing public trust', 'B2GOV_CDC_manager_567', ['reliability', 'trust-risk']),
    ("The retail loyalty program doesn't allow point transfers between family accounts", 'RETAIL_Coca-Cola_manager_890', ['workflow-friction', 'discoverability']),
    ('The legal AI contract reviewer misses jurisdiction-specific clauses, causing compliance risks', 'LEGAL_LegalZoom_manager_123', ['errors', 'compliance']),
    ("The energy smart meter app doesn't show real-time usage, reducing conservation efforts", 'ENERGY_Tesla_Powerwall_end_user_456', ['analytics', 'discoverability']),
    ('The travel hotel check-in app requires manual ID verification, causing lobby queues', 'TRAVEL_Booking_com_end_user_789', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The real estate property listing tool doesn't show flood zone data, misleading buyers", 'REAL_ESTATE_Compas_manager_012', ['discoverability', 'trust-risk']),
    ("The media podcast platform doesn't support offline downloads for premium users", 'MEDIA_Spotify_end_user_345', ['offline-capability', 'workflow-friction']),
    ("The EdTech teacher grading tool doesn't support bulk feedback, increasing workload", 'EDU_Duolingo_manager_678', ['workflow-friction', 'onboarding-cognitive-load']),
    ('The B2B ERP platform requires manual inventory reconciliation after system migrations', 'IT_ENTERPRISE_SAP_manager_901', ['integration-complexity', 'workflow-friction']),
    ("The healthcare patient portal doesn't show lab results in plain language, causing confusion", 'HEALTHCARE_Mayo_Clinic_patient_234', ['accessibility-barrier', 'discoverability']),
    ('The fintech crypto staking platform shows unclear APY calculations, misleading investors', 'FINTECH_Coinbase_manager_567', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry CNC machine interface has no emergency stop visual indicator, risking safety', 'HEAVY_IND_Ge_manager_890', ['accessibility-barrier', 'security']),
    ('The automotive EV battery degradation calculator shows inaccurate estimates, causing buyer hesitation', 'AUTOMOTIVE_Rivian_manager_123', ['trust-risk', 'analytics']),
    ('The consumer electronics smart camera app requires constant cloud subscription for basic playback', 'CONSUMER_ELECTRONICS_Samsung_end_user_456', ['pricing-transparency', 'workflow-friction']),
    ('The B2Gov public transit app shows inaccurate real-time bus locations, causing missed stops', 'B2GOV_City_of_NYC_Services_manager_789', ['reliability', 'trust-risk']),
    ("The retail supply chain dashboard doesn't show supplier carbon footprint, reducing ESG compliance", 'RETAIL_Unilever_manager_012', ['analytics', 'compliance']),
    ('The legal e-filing system rejects documents due to minor formatting errors, causing court delays', 'LEGAL_LexisNexis_manager_345', ['errors', 'workflow-friction']),
    ("The energy grid management system doesn't show renewable energy integration status, causing outages", 'ENERGY_Vestas_manager_678', ['performance-latency', 'trust-risk']),
    ('The travel airline app shows inaccurate baggage fees, causing gate disputes', 'TRAVEL_Expedia_end_user_901', ['pricing-transparency', 'trust-risk']),
    ('The real estate property tax assessment tool uses outdated sales data, causing overpayment', 'REAL_ESTATE_Redfin_manager_234', ['errors', 'pricing-transparency']),
    ('The media streaming service shows inaccurate content ratings, causing parental concerns', 'MEDIA_Audible_manager_567', ['trust-risk', 'discoverability']),
    ("The EdTech student attendance tracker doesn't sync with parent apps, causing communication gaps", 'EDU_Coursera_manager_890', ['cross-platform-sync-issues', 'workflow-friction']),
    ('The B2B marketing platform requires manual A/B testing setup for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_123', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient consent via digital signature", 'HEALTHCARE_Pfizer_manager_456', ['discoverability', 'compliance']),
    ('The fintech lending platform shows unclear APR calculations, misleading borrowers', 'FINTECH_Revolut_end_user_789', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry safety monitoring system sends alerts to wrong departments, causing delays', 'HEAVY_IND_Siemens_manager_012', ['role-permission-confusion', 'workflow-friction']),
    ('The automotive connected car app requires constant GPS permissions, raising privacy concerns', 'AUTOMOTIVE_Ford_end_user_345', ['privacy-data-sensitivity', 'discoverability']),
    ("The consumer electronics smart home app doesn't support Matter protocol, limiting device compatibility", 'CONSUMER_ELECTRONICS_Dyson_manager_678', ['integration-complexity', 'workflow-friction']),
    ('The B2Gov public records portal requires manual form submissions, causing processing delays', 'B2GOV_VA_manager_901', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail inventory management system doesn't show supplier lead times, causing stockouts", 'RETAIL_Walmart_manager_234', ['timeline', 'information-architecture']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Ironclad_manager_567', ['workflow-friction', 'accessibility-barrier']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Enphase_manager_890', ['analytics', 'trust-risk']),
    ('The travel car rental platform shows different insurance costs depending on browser cookies', 'TRAVEL_Expedia_end_user_123', ['pricing-transparency', 'trust-risk']),
    ('The real estate virtual tour feature lags on mobile, causing users to abandon listings', 'REAL_ESTATE_Opendoor_end_user_456', ['performance-latency', 'mobile-parity']),
    ("The media audiobook platform doesn't support background play on iOS, breaking user habits", 'MEDIA_Audible_end_user_789', ['mobile-desktop-parity', 'workflow-friction']),
    ("The EdTech parent portal doesn't show teacher comments, reducing home-school alignment", 'EDU_Duolingo_manager_012', ['discoverability', 'workflow-friction']),
    ('The B2B ITSM platform requires manual ticket routing for cross-departmental issues', 'IT_ENTERPRISE_ServiceNow_manager_345', ['workflow-friction', 'role-permission-confusion']),
    ("The healthcare patient scheduling app doesn't show provider availability in real-time", 'HEALTHCARE_Cerner_patient_678', ['discoverability', 'performance-latency']),
    ('The fintech investment platform shows historical returns without risk-adjusted metrics', 'FINTECH_Fidelity_manager_901', ['analytics', 'trust-risk']),
    ('The heavy industry predictive maintenance system sends false positives, causing unnecessary downtime', 'HEAVY_IND_Boeing_manager_234', ['notification-fatigue', 'trust-risk']),
    ('The automotive keyless entry system fails in cold weather, locking owners out', 'AUTOMOTIVE_Tesla_end_user_567', ['reliability', 'accessibility-barrier']),
    ('The consumer electronics smart speaker app requires constant microphone permissions, raising privacy concerns', 'CONSUMER_ELECTRONICS_Garmin_end_user_890', ['privacy-data-sensitivity', 'discoverability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_LexisNexis_developer_789', ['search', 'semantic-matching']),
    ('The travel flight tracking app shows inaccurate gate changes, causing missed connections', 'TRAVEL_Delta_end_user_345', ['reliability', 'trust-risk']),
    ('The real estate mortgage pre-approval tool uses outdated debt-to-income ratios', 'REAL_ESTATE_Zillow_end_user_678', ['errors', 'pricing-transparency']),
    ('The media news app shows duplicate articles from the same source, reducing content quality', 'MEDIA_NYT_end_user_901', ['workflow-friction', 'discoverability']),
    ('The EdTech exam proctoring system flags legitimate behavior as cheating, causing student distress', 'EDU_Coursera_manager_234', ['trust-risk', 'accessibility-barrier']),
    ('The B2B CRM platform requires manual data entry for every client interaction', 'IT_ENTERPRISE_Salesforce_manager_567', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient-reported outcomes via mobile", 'HEALTHCARE_Pfizer_manager_890', ['mobile-parity', 'workflow-friction']),
    ('The fintech insurance platform shows premiums without explaining coverage gaps', 'FINTECH_Revolut_end_user_123', ['pricing-transparency', 'discoverability']),
    ('The heavy industry drone inspection system fails in high winds, delaying safety checks', 'HEAVY_IND_Caterpillar_field_worker_456', ['reliability', 'performance-latency']),
    ('The automotive connected car app requires a monthly subscription for basic navigation updates', 'AUTOMOTIVE_BMW_end_user_789', ['pricing-transparency', 'trust-risk']),
    ("The consumer electronics smart lock app doesn't work with standard Android keychains", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_012', ['cross-platform-sync-issues', 'integration-complexity']),
    ('The B2Gov public health dashboard shows outdated case counts, reducing public trust', 'B2GOV_CDC_manager_345', ['reliability', 'trust-risk']),
    ("The retail loyalty program doesn't allow point transfers between family accounts", 'RETAIL_Coca-Cola_manager_678', ['workflow-friction', 'discoverability']),
    ('The legal AI contract reviewer misses jurisdiction-specific clauses, causing compliance risks', 'LEGAL_LegalZoom_manager_901', ['errors', 'compliance']),
    ("The energy smart meter app doesn't show real-time usage, reducing conservation efforts", 'ENERGY_Tesla_Powerwall_end_user_234', ['analytics', 'discoverability']),
    ('The travel hotel check-in app requires manual ID verification, causing lobby queues', 'TRAVEL_Booking_com_end_user_567', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The real estate property listing tool doesn't show flood zone data, misleading buyers", 'REAL_ESTATE_Compas_manager_890', ['discoverability', 'trust-risk']),
    ("The media podcast platform doesn't support offline downloads for premium users", 'MEDIA_Spotify_end_user_123', ['offline-capability', 'workflow-friction']),
    ("The EdTech teacher grading tool doesn't support bulk feedback, increasing workload", 'EDU_Duolingo_manager_456', ['workflow-friction', 'onboarding-cognitive-load']),
    ('The B2B ERP platform requires manual inventory reconciliation after system migrations', 'IT_ENTERPRISE_SAP_manager_789', ['integration-complexity', 'workflow-friction']),
    ("The healthcare patient portal doesn't show lab results in plain language, causing confusion", 'HEALTHCARE_Mayo_Clinic_patient_012', ['accessibility-barrier', 'discoverability']),
    ('The fintech crypto staking platform shows unclear APY calculations, misleading investors', 'FINTECH_Coinbase_manager_345', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry CNC machine interface has no emergency stop visual indicator, risking safety', 'HEAVY_IND_Ge_manager_678', ['accessibility-barrier', 'security']),
    ('The automotive EV battery degradation calculator shows inaccurate estimates, causing buyer hesitation', 'AUTOMOTIVE_Rivian_manager_901', ['trust-risk', 'analytics']),
    ('The consumer electronics smart camera app requires constant cloud subscription for basic playback', 'CONSUMER_ELECTRONICS_Samsung_end_user_234', ['pricing-transparency', 'workflow-friction']),
    ('The B2Gov public transit app shows inaccurate real-time bus locations, causing missed stops', 'B2GOV_City_of_NYC_Services_manager_567', ['reliability', 'trust-risk']),
    ("The retail supply chain dashboard doesn't show supplier carbon footprint, reducing ESG compliance", 'RETAIL_Unilever_manager_890', ['analytics', 'compliance']),
    ('The legal e-filing system rejects documents due to minor formatting errors, causing court delays', 'LEGAL_LexisNexis_manager_123', ['errors', 'workflow-friction']),
    ("The energy grid management system doesn't show renewable energy integration status, causing outages", 'ENERGY_Vestas_manager_456', ['performance-latency', 'trust-risk']),
    ('The travel airline app shows inaccurate baggage fees, causing gate disputes', 'TRAVEL_Expedia_end_user_789', ['pricing-transparency', 'trust-risk']),
    ('The real estate property tax assessment tool uses outdated sales data, causing overpayment', 'REAL_ESTATE_Redfin_manager_012', ['errors', 'pricing-transparency']),
    ('The media streaming service shows inaccurate content ratings, causing parental concerns', 'MEDIA_Audible_manager_345', ['trust-risk', 'discoverability']),
    ("The EdTech student attendance tracker doesn't sync with parent apps, causing communication gaps", 'EDU_Coursera_manager_678', ['cross-platform-sync-issues', 'workflow-friction']),
    ('The B2B marketing platform requires manual A/B testing setup for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_901', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient consent via digital signature", 'HEALTHCARE_Pfizer_manager_234', ['discoverability', 'compliance']),
    ('The fintech lending platform shows unclear APR calculations, misleading borrowers', 'FINTECH_Revolut_end_user_567', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry safety monitoring system sends alerts to wrong departments, causing delays', 'HEAVY_IND_Siemens_manager_890', ['role-permission-confusion', 'workflow-friction']),
    ('The automotive connected car app requires constant GPS permissions, raising privacy concerns', 'AUTOMOTIVE_Ford_end_user_123', ['privacy-data-sensitivity', 'discoverability']),
    ("The consumer electronics smart home app doesn't support Matter protocol, limiting device compatibility", 'CONSUMER_ELECTRONICS_Dyson_manager_456', ['integration-complexity', 'workflow-friction']),
    ('The B2Gov public records portal requires manual form submissions, causing processing delays', 'B2GOV_VA_manager_789', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail inventory management system doesn't show supplier lead times, causing stockouts", 'RETAIL_Walmart_manager_012', ['timeline', 'information-architecture']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Ironclad_manager_345', ['workflow-friction', 'accessibility-barrier']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Enphase_manager_678', ['analytics', 'trust-risk']),
    ('The travel car rental platform shows different insurance costs depending on browser cookies', 'TRAVEL_Expedia_end_user_901', ['pricing-transparency', 'trust-risk']),
    ('The real estate virtual tour feature lags on mobile, causing users to abandon listings', 'REAL_ESTATE_Opendoor_end_user_234', ['performance-latency', 'mobile-parity']),
    ("The media audiobook platform doesn't support background play on iOS, breaking user habits", 'MEDIA_Audible_end_user_567', ['mobile-desktop-parity', 'workflow-friction']),
    ("The EdTech parent portal doesn't show teacher comments, reducing home-school alignment", 'EDU_Duolingo_manager_890', ['discoverability', 'workflow-friction']),
    ('The B2B ITSM platform requires manual ticket routing for cross-departmental issues', 'IT_ENTERPRISE_ServiceNow_manager_123', ['workflow-friction', 'role-permission-confusion']),
    ("The healthcare patient scheduling app doesn't show provider availability in real-time", 'HEALTHCARE_Cerner_patient_456', ['discoverability', 'performance-latency']),
    ('The fintech investment platform shows historical returns without risk-adjusted metrics', 'FINTECH_Fidelity_manager_789', ['analytics', 'trust-risk']),
    ('The heavy industry predictive maintenance system sends false positives, causing unnecessary downtime', 'HEAVY_IND_Boeing_manager_012', ['notification-fatigue', 'trust-risk']),
    ('The automotive keyless entry system fails in cold weather, locking owners out', 'AUTOMOTIVE_Tesla_end_user_345', ['reliability', 'accessibility-barrier']),
    ('The consumer electronics smart speaker app requires constant microphone permissions, raising privacy concerns', 'CONSUMER_ELECTRONICS_Garmin_end_user_678', ['privacy-data-sensitivity', 'discoverability']),
    ('The B2Gov voter registration portal times out during peak hours, losing applications', 'B2GOV_DMV_end_user_901', ['reliability', 'state-persistence']),
    ('The retail POS system crashes during holiday sales, causing checkout queues', 'RETAIL_Walmart_manager_234', ['performance-latency', 'reliability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_LexisNexis_developer_567', ['search', 'semantic-matching']),
    ("The energy utility billing app doesn't show usage breakdowns by appliance, reducing engagement", 'ENERGY_Enphase_end_user_890', ['analytics', 'discoverability']),
    ('The travel flight tracking app shows inaccurate gate changes, causing missed connections', 'TRAVEL_Delta_end_user_123', ['reliability', 'trust-risk']),
    ('The real estate mortgage pre-approval tool uses outdated debt-to-income ratios', 'REAL_ESTATE_Zillow_end_user_456', ['errors', 'pricing-transparency']),
    ('The media news app shows duplicate articles from the same source, reducing content quality', 'MEDIA_NYT_end_user_789', ['workflow-friction', 'discoverability']),
    ('The EdTech exam proctoring system flags legitimate behavior as cheating, causing student distress', 'EDU_Coursera_manager_012', ['trust-risk', 'accessibility-barrier']),
    ('The B2B CRM platform requires manual data entry for every client interaction', 'IT_ENTERPRISE_Salesforce_manager_345', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient-reported outcomes via mobile", 'HEALTHCARE_Pfizer_manager_678', ['mobile-parity', 'workflow-friction']),
    ('The fintech insurance platform shows premiums without explaining coverage gaps', 'FINTECH_Revolut_end_user_901', ['pricing-transparency', 'discoverability']),
    ('The heavy industry drone inspection system fails in high winds, delaying safety checks', 'HEAVY_IND_Caterpillar_field_worker_234', ['reliability', 'performance-latency']),
    ('The automotive connected car app requires a monthly subscription for basic navigation updates', 'AUTOMOTIVE_BMW_end_user_567', ['pricing-transparency', 'trust-risk']),
    ("The consumer electronics smart lock app doesn't work with standard Android keychains", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_890', ['cross-platform-sync-issues', 'integration-complexity']),
    ('The B2Gov public health dashboard shows outdated case counts, reducing public trust', 'B2GOV_CDC_manager_123', ['reliability', 'trust-risk']),
    ("The retail loyalty program doesn't allow point transfers between family accounts", 'RETAIL_Coca-Cola_manager_456', ['workflow-friction', 'discoverability']),
    ('The legal AI contract reviewer misses jurisdiction-specific clauses, causing compliance risks', 'LEGAL_LegalZoom_manager_789', ['errors', 'compliance']),
    ("The energy smart meter app doesn't show real-time usage, reducing conservation efforts", 'ENERGY_Tesla_Powerwall_end_user_012', ['analytics', 'discoverability']),
    ('The travel hotel check-in app requires manual ID verification, causing lobby queues', 'TRAVEL_Booking_com_end_user_345', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The real estate property listing tool doesn't show flood zone data, misleading buyers", 'REAL_ESTATE_Compas_manager_678', ['discoverability', 'trust-risk']),
    ("The media podcast platform doesn't support offline downloads for premium users", 'MEDIA_Spotify_end_user_901', ['offline-capability', 'workflow-friction']),
    ("The EdTech teacher grading tool doesn't support bulk feedback, increasing workload", 'EDU_Duolingo_manager_234', ['workflow-friction', 'onboarding-cognitive-load']),
    ('The B2B ERP platform requires manual inventory reconciliation after system migrations', 'IT_ENTERPRISE_SAP_manager_567', ['integration-complexity', 'workflow-friction']),
    ("The healthcare patient portal doesn't show lab results in plain language, causing confusion", 'HEALTHCARE_Mayo_Clinic_patient_890', ['accessibility-barrier', 'discoverability']),
    ('The fintech crypto staking platform shows unclear APY calculations, misleading investors', 'FINTECH_Coinbase_manager_123', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry CNC machine interface has no emergency stop visual indicator, risking safety', 'HEAVY_IND_Ge_manager_456', ['accessibility-barrier', 'security']),
    ('The automotive EV battery degradation calculator shows inaccurate estimates, causing buyer hesitation', 'AUTOMOTIVE_Rivian_manager_789', ['trust-risk', 'analytics']),
    ('The consumer electronics smart camera app requires constant cloud subscription for basic playback', 'CONSUMER_ELECTRONICS_Samsung_end_user_012', ['pricing-transparency', 'workflow-friction']),
    ('The B2Gov public transit app shows inaccurate real-time bus locations, causing missed stops', 'B2GOV_City_of_NYC_Services_manager_345', ['reliability', 'trust-risk']),
    ("The retail supply chain dashboard doesn't show supplier carbon footprint, reducing ESG compliance", 'RETAIL_Unilever_manager_678', ['analytics', 'compliance']),
    ('The legal e-filing system rejects documents due to minor formatting errors, causing court delays', 'LEGAL_LexisNexis_manager_901', ['errors', 'workflow-friction']),
    ("The energy grid management system doesn't show renewable energy integration status, causing outages", 'ENERGY_Vestas_manager_234', ['performance-latency', 'trust-risk']),
    ('The travel airline app shows inaccurate baggage fees, causing gate disputes', 'TRAVEL_Expedia_end_user_567', ['pricing-transparency', 'trust-risk']),
    ('The real estate property tax assessment tool uses outdated sales data, causing overpayment', 'REAL_ESTATE_Redfin_manager_890', ['errors', 'pricing-transparency']),
    ('The media streaming service shows inaccurate content ratings, causing parental concerns', 'MEDIA_Audible_manager_123', ['trust-risk', 'discoverability']),
    ("The EdTech student attendance tracker doesn't sync with parent apps, causing communication gaps", 'EDU_Coursera_manager_456', ['cross-platform-sync-issues', 'workflow-friction']),
    ('The B2B marketing platform requires manual A/B testing setup for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_789', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient consent via digital signature", 'HEALTHCARE_Pfizer_manager_012', ['discoverability', 'compliance']),
    ('The fintech lending platform shows unclear APR calculations, misleading borrowers', 'FINTECH_Revolut_end_user_345', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry safety monitoring system sends alerts to wrong departments, causing delays', 'HEAVY_IND_Siemens_manager_678', ['role-permission-confusion', 'workflow-friction']),
    ('The automotive connected car app requires constant GPS permissions, raising privacy concerns', 'AUTOMOTIVE_Ford_end_user_901', ['privacy-data-sensitivity', 'discoverability']),
    ("The consumer electronics smart home app doesn't support Matter protocol, limiting device compatibility", 'CONSUMER_ELECTRONICS_Dyson_manager_234', ['integration-complexity', 'workflow-friction']),
    ('The B2Gov public records portal requires manual form submissions, causing processing delays', 'B2GOV_VA_manager_567', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail inventory management system doesn't show supplier lead times, causing stockouts", 'RETAIL_Walmart_manager_890', ['timeline', 'information-architecture']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Ironclad_manager_123', ['workflow-friction', 'accessibility-barrier']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Enphase_manager_456', ['analytics', 'trust-risk']),
    ('The travel car rental platform shows different insurance costs depending on browser cookies', 'TRAVEL_Expedia_end_user_789', ['pricing-transparency', 'trust-risk']),
    ('The real estate virtual tour feature lags on mobile, causing users to abandon listings', 'REAL_ESTATE_Opendoor_end_user_012', ['performance-latency', 'mobile-parity']),
    ("The media audiobook platform doesn't support background play on iOS, breaking user habits", 'MEDIA_Audible_end_user_345', ['mobile-desktop-parity', 'workflow-friction']),
    ("The EdTech parent portal doesn't show teacher comments, reducing home-school alignment", 'EDU_Duolingo_manager_678', ['discoverability', 'workflow-friction']),
    ('The B2B ITSM platform requires manual ticket routing for cross-departmental issues', 'IT_ENTERPRISE_ServiceNow_manager_901', ['workflow-friction', 'role-permission-confusion']),
    ("The healthcare patient scheduling app doesn't show provider availability in real-time", 'HEALTHCARE_Cerner_patient_234', ['discoverability', 'performance-latency']),
    ('The fintech investment platform shows historical returns without risk-adjusted metrics', 'FINTECH_Fidelity_manager_567', ['analytics', 'trust-risk']),
    ('The heavy industry predictive maintenance system sends false positives, causing unnecessary downtime', 'HEAVY_IND_Boeing_manager_890', ['notification-fatigue', 'trust-risk']),
    ('The automotive keyless entry system fails in cold weather, locking owners out', 'AUTOMOTIVE_Tesla_end_user_123', ['reliability', 'accessibility-barrier']),
    ('The consumer electronics smart speaker app requires constant microphone permissions, raising privacy concerns', 'CONSUMER_ELECTRONICS_Garmin_end_user_456', ['privacy-data-sensitivity', 'discoverability']),
    ('The B2Gov voter registration portal times out during peak hours, losing applications', 'B2GOV_DMV_end_user_789', ['reliability', 'state-persistence']),
    ('The retail POS system crashes during holiday sales, causing checkout queues', 'RETAIL_Walmart_manager_012', ['performance-latency', 'reliability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_LexisNexis_developer_345', ['search', 'semantic-matching']),
    ("The energy utility billing app doesn't show usage breakdowns by appliance, reducing engagement", 'ENERGY_Enphase_end_user_678', ['analytics', 'discoverability']),
    ('The travel flight tracking app shows inaccurate gate changes, causing missed connections', 'TRAVEL_Delta_end_user_901', ['reliability', 'trust-risk']),
    ('The real estate mortgage pre-approval tool uses outdated debt-to-income ratios', 'REAL_ESTATE_Zillow_end_user_234', ['errors', 'pricing-transparency']),
    ('The media news app shows duplicate articles from the same source, reducing content quality', 'MEDIA_NYT_end_user_567', ['workflow-friction', 'discoverability']),
    ('The EdTech exam proctoring system flags legitimate behavior as cheating, causing student distress', 'EDU_Coursera_manager_890', ['trust-risk', 'accessibility-barrier']),
    ('The B2B CRM platform requires manual data entry for every client interaction', 'IT_ENTERPRISE_Salesforce_manager_123', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient-reported outcomes via mobile", 'HEALTHCARE_Pfizer_manager_456', ['mobile-parity', 'workflow-friction']),
    ('The fintech insurance platform shows premiums without explaining coverage gaps', 'FINTECH_Revolut_end_user_789', ['pricing-transparency', 'discoverability']),
    ('The heavy industry drone inspection system fails in high winds, delaying safety checks', 'HEAVY_IND_Caterpillar_field_worker_012', ['reliability', 'performance-latency']),
    ('The automotive connected car app requires a monthly subscription for basic navigation updates', 'AUTOMOTIVE_BMW_end_user_345', ['pricing-transparency', 'trust-risk']),
    ("The consumer electronics smart lock app doesn't work with standard Android keychains", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_678', ['cross-platform-sync-issues', 'integration-complexity']),
    ('The B2Gov public health dashboard shows outdated case counts, reducing public trust', 'B2GOV_CDC_manager_901', ['reliability', 'trust-risk']),
    ("The retail loyalty program doesn't allow point transfers between family accounts", 'RETAIL_Coca-Cola_manager_234', ['workflow-friction', 'discoverability']),
    ('The legal AI contract reviewer misses jurisdiction-specific clauses, causing compliance risks', 'LEGAL_LegalZoom_manager_567', ['errors', 'compliance']),
    ("The energy smart meter app doesn't show real-time usage, reducing conservation efforts", 'ENERGY_Tesla_Powerwall_end_user_890', ['analytics', 'discoverability']),
    ('The travel hotel check-in app requires manual ID verification, causing lobby queues', 'TRAVEL_Booking_com_end_user_123', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The real estate property listing tool doesn't show flood zone data, misleading buyers", 'REAL_ESTATE_Compas_manager_456', ['discoverability', 'trust-risk']),
    ("The media podcast platform doesn't support offline downloads for premium users", 'MEDIA_Spotify_end_user_789', ['offline-capability', 'workflow-friction']),
    ("The EdTech teacher grading tool doesn't support bulk feedback, increasing workload", 'EDU_Duolingo_manager_012', ['workflow-friction', 'onboarding-cognitive-load']),
    ('The B2B ERP platform requires manual inventory reconciliation after system migrations', 'IT_ENTERPRISE_SAP_manager_345', ['integration-complexity', 'workflow-friction']),
    ("The healthcare patient portal doesn't show lab results in plain language, causing confusion", 'HEALTHCARE_Mayo_Clinic_patient_678', ['accessibility-barrier', 'discoverability']),
    ('The fintech crypto staking platform shows unclear APY calculations, misleading investors', 'FINTECH_Coinbase_manager_901', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry CNC machine interface has no emergency stop visual indicator, risking safety', 'HEAVY_IND_Ge_manager_234', ['accessibility-barrier', 'security']),
    ('The automotive EV battery degradation calculator shows inaccurate estimates, causing buyer hesitation', 'AUTOMOTIVE_Rivian_manager_567', ['trust-risk', 'analytics']),
    ('The consumer electronics smart camera app requires constant cloud subscription for basic playback', 'CONSUMER_ELECTRONICS_Samsung_end_user_890', ['pricing-transparency', 'workflow-friction']),
    ('The B2Gov public transit app shows inaccurate real-time bus locations, causing missed stops', 'B2GOV_City_of_NYC_Services_manager_123', ['reliability', 'trust-risk']),
    ("The retail supply chain dashboard doesn't show supplier carbon footprint, reducing ESG compliance", 'RETAIL_Unilever_manager_456', ['analytics', 'compliance']),
    ('The legal e-filing system rejects documents due to minor formatting errors, causing court delays', 'LEGAL_LexisNexis_manager_789', ['errors', 'workflow-friction']),
    ("The energy grid management system doesn't show renewable energy integration status, causing outages", 'ENERGY_Vestas_manager_012', ['performance-latency', 'trust-risk']),
    ('The travel airline app shows inaccurate baggage fees, causing gate disputes', 'TRAVEL_Expedia_end_user_345', ['pricing-transparency', 'trust-risk']),
    ('The real estate property tax assessment tool uses outdated sales data, causing overpayment', 'REAL_ESTATE_Redfin_manager_678', ['errors', 'pricing-transparency']),
    ('The media streaming service shows inaccurate content ratings, causing parental concerns', 'MEDIA_Audible_manager_901', ['trust-risk', 'discoverability']),
    ("The EdTech student attendance tracker doesn't sync with parent apps, causing communication gaps", 'EDU_Coursera_manager_234', ['cross-platform-sync-issues', 'workflow-friction']),
    ('The B2B marketing platform requires manual A/B testing setup for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_567', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient consent via digital signature", 'HEALTHCARE_Pfizer_manager_890', ['discoverability', 'compliance']),
    ('The fintech lending platform shows unclear APR calculations, misleading borrowers', 'FINTECH_Revolut_end_user_123', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry safety monitoring system sends alerts to wrong departments, causing delays', 'HEAVY_IND_Siemens_manager_456', ['role-permission-confusion', 'workflow-friction']),
    ('The automotive connected car app requires constant GPS permissions, raising privacy concerns', 'AUTOMOTIVE_Ford_end_user_789', ['privacy-data-sensitivity', 'discoverability']),
    ("The consumer electronics smart home app doesn't support Matter protocol, limiting device compatibility", 'CONSUMER_ELECTRONICS_Dyson_manager_012', ['integration-complexity', 'workflow-friction']),
    ('The B2Gov public records portal requires manual form submissions, causing processing delays', 'B2GOV_VA_manager_345', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail inventory management system doesn't show supplier lead times, causing stockouts", 'RETAIL_Walmart_manager_678', ['timeline', 'information-architecture']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Ironclad_manager_901', ['workflow-friction', 'accessibility-barrier']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Enphase_manager_234', ['analytics', 'trust-risk']),
    ('The travel car rental platform shows different insurance costs depending on browser cookies', 'TRAVEL_Expedia_end_user_567', ['pricing-transparency', 'trust-risk']),
    ('The real estate virtual tour feature lags on mobile, causing users to abandon listings', 'REAL_ESTATE_Opendoor_end_user_890', ['performance-latency', 'mobile-parity']),
    ("The media audiobook platform doesn't support background play on iOS, breaking user habits", 'MEDIA_Audible_end_user_123', ['mobile-desktop-parity', 'workflow-friction']),
    ("The EdTech parent portal doesn't show teacher comments, reducing home-school alignment", 'EDU_Duolingo_manager_456', ['discoverability', 'workflow-friction']),
    ('The B2B ITSM platform requires manual ticket routing for cross-departmental issues', 'IT_ENTERPRISE_ServiceNow_manager_789', ['workflow-friction', 'role-permission-confusion']),
    ("The healthcare patient scheduling app doesn't show provider availability in real-time", 'HEALTHCARE_Cerner_patient_012', ['discoverability', 'performance-latency']),
    ('The fintech investment platform shows historical returns without risk-adjusted metrics', 'FINTECH_Fidelity_manager_345', ['analytics', 'trust-risk']),
    ('The heavy industry predictive maintenance system sends false positives, causing unnecessary downtime', 'HEAVY_IND_Boeing_manager_678', ['notification-fatigue', 'trust-risk']),
    ('The automotive keyless entry system fails in cold weather, locking owners out', 'AUTOMOTIVE_Tesla_end_user_901', ['reliability', 'accessibility-barrier']),
    ('The consumer electronics smart speaker app requires constant microphone permissions, raising privacy concerns', 'CONSUMER_ELECTRONICS_Garmin_end_user_234', ['privacy-data-sensitivity', 'discoverability']),
    ('The B2Gov voter registration portal times out during peak hours, losing applications', 'B2GOV_DMV_end_user_567', ['reliability', 'state-persistence']),
    ('The retail POS system crashes during holiday sales, causing checkout queues', 'RETAIL_Walmart_manager_890', ['performance-latency', 'reliability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_LexisNexis_developer_123', ['search', 'semantic-matching']),
    ("The energy utility billing app doesn't show usage breakdowns by appliance, reducing engagement", 'ENERGY_Enphase_end_user_456', ['analytics', 'discoverability']),
    ('The travel flight tracking app shows inaccurate gate changes, causing missed connections', 'TRAVEL_Delta_end_user_789', ['reliability', 'trust-risk']),
    ('The real estate mortgage pre-approval tool uses outdated debt-to-income ratios', 'REAL_ESTATE_Zillow_end_user_012', ['errors', 'pricing-transparency']),
    ('The media news app shows duplicate articles from the same source, reducing content quality', 'MEDIA_NYT_end_user_345', ['workflow-friction', 'discoverability']),
    ('The EdTech exam proctoring system flags legitimate behavior as cheating, causing student distress', 'EDU_Coursera_manager_678', ['trust-risk', 'accessibility-barrier']),
    ('The B2B CRM platform requires manual data entry for every client interaction', 'IT_ENTERPRISE_Salesforce_manager_901', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient-reported outcomes via mobile", 'HEALTHCARE_Pfizer_manager_234', ['mobile-parity', 'workflow-friction']),
    ('The fintech insurance platform shows premiums without explaining coverage gaps', 'FINTECH_Revolut_end_user_567', ['pricing-transparency', 'discoverability']),
    ('The heavy industry drone inspection system fails in high winds, delaying safety checks', 'HEAVY_IND_Caterpillar_field_worker_890', ['reliability', 'performance-latency']),
    ('The automotive connected car app requires a monthly subscription for basic navigation updates', 'AUTOMOTIVE_BMW_end_user_123', ['pricing-transparency', 'trust-risk']),
    ("The consumer electronics smart lock app doesn't work with standard Android keychains", 'CONSUMER_ELECTRONICS_Apple_Watch_end_user_456', ['cross-platform-sync-issues', 'integration-complexity']),
    ('The B2Gov public health dashboard shows outdated case counts, reducing public trust', 'B2GOV_CDC_manager_789', ['reliability', 'trust-risk']),
    ("The retail loyalty program doesn't allow point transfers between family accounts", 'RETAIL_Coca-Cola_manager_012', ['workflow-friction', 'discoverability']),
    ('The legal AI contract reviewer misses jurisdiction-specific clauses, causing compliance risks', 'LEGAL_LegalZoom_manager_345', ['errors', 'compliance']),
    ("The energy smart meter app doesn't show real-time usage, reducing conservation efforts", 'ENERGY_Tesla_Powerwall_end_user_678', ['analytics', 'discoverability']),
    ('The travel hotel check-in app requires manual ID verification, causing lobby queues', 'TRAVEL_Booking_com_end_user_901', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The real estate property listing tool doesn't show flood zone data, misleading buyers", 'REAL_ESTATE_Compas_manager_234', ['discoverability', 'trust-risk']),
    ("The media podcast platform doesn't support offline downloads for premium users", 'MEDIA_Spotify_end_user_567', ['offline-capability', 'workflow-friction']),
    ("The EdTech teacher grading tool doesn't support bulk feedback, increasing workload", 'EDU_Duolingo_manager_890', ['workflow-friction', 'onboarding-cognitive-load']),
    ('The B2B ERP platform requires manual inventory reconciliation after system migrations', 'IT_ENTERPRISE_SAP_manager_123', ['integration-complexity', 'workflow-friction']),
    ("The healthcare patient portal doesn't show lab results in plain language, causing confusion", 'HEALTHCARE_Mayo_Clinic_patient_456', ['accessibility-barrier', 'discoverability']),
    ('The fintech crypto staking platform shows unclear APY calculations, misleading investors', 'FINTECH_Coinbase_manager_789', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry CNC machine interface has no emergency stop visual indicator, risking safety', 'HEAVY_IND_Ge_manager_012', ['accessibility-barrier', 'security']),
    ('The automotive EV battery degradation calculator shows inaccurate estimates, causing buyer hesitation', 'AUTOMOTIVE_Rivian_manager_345', ['trust-risk', 'analytics']),
    ('The consumer electronics smart camera app requires constant cloud subscription for basic playback', 'CONSUMER_ELECTRONICS_Samsung_end_user_678', ['pricing-transparency', 'workflow-friction']),
    ('The B2Gov public transit app shows inaccurate real-time bus locations, causing missed stops', 'B2GOV_City_of_NYC_Services_manager_901', ['reliability', 'trust-risk']),
    ("The retail supply chain dashboard doesn't show supplier carbon footprint, reducing ESG compliance", 'RETAIL_Unilever_manager_234', ['analytics', 'compliance']),
    ('The legal e-filing system rejects documents due to minor formatting errors, causing court delays', 'LEGAL_LexisNexis_manager_567', ['errors', 'workflow-friction']),
    ("The energy grid management system doesn't show renewable energy integration status, causing outages", 'ENERGY_Vestas_manager_890', ['performance-latency', 'trust-risk']),
    ('The travel airline app shows inaccurate baggage fees, causing gate disputes', 'TRAVEL_Expedia_end_user_123', ['pricing-transparency', 'trust-risk']),
    ('The real estate property tax assessment tool uses outdated sales data, causing overpayment', 'REAL_ESTATE_Redfin_manager_456', ['errors', 'pricing-transparency']),
    ('The media streaming service shows inaccurate content ratings, causing parental concerns', 'MEDIA_Audible_manager_789', ['trust-risk', 'discoverability']),
    ("The EdTech student attendance tracker doesn't sync with parent apps, causing communication gaps", 'EDU_Coursera_manager_012', ['cross-platform-sync-issues', 'workflow-friction']),
    ('The B2B marketing platform requires manual A/B testing setup for every campaign', 'IT_ENTERPRISE_Microsoft_365_manager_345', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The healthcare clinical trial portal doesn't allow patient consent via digital signature", 'HEALTHCARE_Pfizer_manager_678', ['discoverability', 'compliance']),
    ('The fintech lending platform shows unclear APR calculations, misleading borrowers', 'FINTECH_Revolut_end_user_901', ['pricing-transparency', 'trust-risk']),
    ('The heavy industry safety monitoring system sends alerts to wrong departments, causing delays', 'HEAVY_IND_Siemens_manager_234', ['role-permission-confusion', 'workflow-friction']),
    ('The automotive connected car app requires constant GPS permissions, raising privacy concerns', 'AUTOMOTIVE_Ford_end_user_567', ['privacy-data-sensitivity', 'discoverability']),
    ("The consumer electronics smart home app doesn't support Matter protocol, limiting device compatibility", 'CONSUMER_ELECTRONICS_Dyson_manager_890', ['integration-complexity', 'workflow-friction']),
    ('The B2Gov public records portal requires manual form submissions, causing processing delays', 'B2GOV_VA_manager_123', ['onboarding-cognitive-load', 'workflow-friction']),
    ("The retail inventory management system doesn't show supplier lead times, causing stockouts", 'RETAIL_Walmart_manager_456', ['timeline', 'information-architecture']),
    ('The legal contract comparison tool highlights irrelevant differences, wasting review time', 'LEGAL_Ironclad_manager_789', ['workflow-friction', 'accessibility-barrier']),
    ("The energy solar panel monitoring app doesn't show degradation trends over time", 'ENERGY_Enphase_manager_012', ['analytics', 'trust-risk']),
    ('The B2Gov voter registration portal times out during peak hours, losing applications', 'B2GOV_DMV_end_user_345', ['reliability', 'state-persistence']),
    ('The retail POS system crashes during holiday sales, causing checkout queues', 'RETAIL_Walmart_manager_678', ['performance-latency', 'reliability']),
    ("The legal contract review tool misses key clauses because it doesn't understand our firm's terminology", 'LEGAL_LexisNexis_developer_901', ['search', 'semantic-matching']),
    ("The energy utility billing app doesn't show usage breakdowns by appliance, reducing engagement", 'ENERGY_Enphase_end_user_234', ['analytics', 'discoverability']),
    ('ANOVA result for navigation menus: F(2, 58) = 5.43, p = 0.007', 'QUANT_STATS_001', ['stats', 'anova', 'navigation']),
    ('Average SUS score for the new dashboard: 72.4 (Grade: B-)', 'USER_SURVEY_002', ['sus', 'usability']),
    ('95% Confidence Interval for task success: [0.65, 0.82]', 'STATS_ENGINE_003', ['confidence-interval', 'stats']),
    ("Fitts's Law prediction: Target ID=4.2 bits, MT=1450ms", 'HCI_LAB_004', ['fitts-law', 'interaction']),
    ('NPS (Net Promoter Score): +24 (Promoters: 45%, Passives: 34%, Detractors: 21%)', 'SURVEY_MONKEY_005', ['nps', 'loyalty']),
    ('UMUX-Lite score: 78.2/100 (Adjusted for SUS parity: 81.5)', 'UX_METRICS_006', ['umux-lite', 'usability']),
    ('Task Completion Time (Mean): 42.5s (SD = 8.4s, n=12)', 'USABILITY_LOG_007', ['time-on-task', 'performance']),
    ('Error rate on the Checkout step: 14.2% (p < 0.05 vs baseline)', 'ANALYTICS_CHECKOUT_008', ['error-rate', 'conversion']),
    ('MaxDiff utility score for "Privacy": 1.62 (Ranked #1 of 8 features)', 'MARKET_RES_009', ['maxdiff', 'prioritization']),
    ('Conjoint trade-off: Users value "Price" 2.5x more than "Speed"', 'CONJOINT_OUTPUT_010', ['conjoint-analysis', 'pricing']),
    ('Regression R-squared: 0.68 for correlation between "Experience" and "Retention"', 'DS_MODEL_011', ['regression', 'stats']),
    ('K-means Cluster 3: "Power Users" (n=450), 85% feature adoption rate', 'SEGMENTATION_012', ['clustering', 'behavioral-segmentation']),
    ('Eye-tracking Fixation Duration (Avg): 240ms on Hero Image', 'EYE_TRACK_013', ['eye-tracking', 'attention']),
    ('GOMS Model execution time: 12.8s for expert users', 'KLM_MODEL_014', ['goms', 'expert-performance']),
    ('Bayesian probability of B outperforming A: 94.8%', 'AB_TEST_015', ['bayesian', 'ab-test']),
    ('Average SEQ (Single Ease Question) score: 5.8/7', 'POST_TASK_016', ['seq', 'usability']),
    ('Churn rate (30-day): 8.4% (Highest in "Trial" cohort)', 'RETAIN_017', ['churn', 'retention']),
    ('Factor loading for "Trust" construct: 0.82 (Cronbach Alpha: 0.88)', 'SURVEY_VAL_018', ['factor-analysis', 'validity']),
    ('Mean time between failures (MTBF): 142 hours', 'INDUSTRIAL_LOG_019', ['reliability', 'mtbf']),
    ('Stripe Payout reconciliation error: 0.04% of transactions', 'FINTECH_AUDIT_020', ['accuracy', 'reconciliation']),
    ('Click-through rate (CTR): 2.15% (Target: 3.5%)', 'MARKETING_LOG_021', ['ctr', 'conversion']),
    ('Linear regression coefficient for "Loading Time": -0.45 per second', 'PERF_ANALYSIS_022', ['regression', 'performance']),
    ('Structural Equation Model (SEM) path coefficient (UI -> Satisfaction): 0.65', 'ACADEMIC_RES_023', ['sem', 'user-experience']),
    ('Markov chain probability: Home -> Product -> Cart = 0.12', 'CLICKSTREAM_024', ['markov-chain', 'path-analysis']),
    ('User retention Day 90: 14.5% (Benchmark: 12%)', 'KPI_REPORT_025', ['retention', 'kpi']),
    ('Average LTV (Lifetime Value): $1,240 (CAC: $450)', 'BUSINESS_UNIT_026', ['ltv', 'cac']),
    ('Monte Carlo simulation: 85% chance of project completion in 4 weeks', 'PLANNING_TOOL_027', ['monte-carlo', 'risk']),
    ('System Usability Scale (SUS) SD: 12.4 (n=50)', 'SURVEY_RAW_028', ['sus', 'stats']),
    ('90th percentile load time: 1.2s', 'SRE_METRICS_029', ['latency', 'performance']),
    ('Conversion lift (Variant C): +12.5% (p=0.002)', 'EXPERIMENT_030', ['ab-test', 'lift']),
    ('Item Response Theory (IRT) difficulty parameter: b=1.45', 'SURVEY_ENGINE_031', ['irt', 'psychometrics']),
    ('Pupillometry dilation: 15% increase during high cognitive load task', 'BIOMETRIC_032', ['pupillometry', 'cognitive-load']),
    ('EEG Alpha power suppression: 22% during task execution', 'NEURO_UX_033', ['eeg', 'attention']),
    ('Kano Model: "Advanced Filters" = Attractive (Coefficient: 0.72)', 'FEATURE_IDEATION_034', ['kano-model', 'prioritization']),
    ('Time-on-page (Median): 48s for "Help" documentation', 'DOC_STATS_035', ['engagement', 'readability']),
    ('Averge Page Load Time: 2.8s (Mobile: 4.5s)', 'WEB_VITALS_036', ['performance', 'mobile-latency']),
    ('Net Promoter Score (NPS) p-value: 0.12 (not significant vs last quarter)', 'QUARTERLY_037', ['stats', 'nps']),
    ('Logistic regression: Odds Ratio = 2.4 for "Tutorial Completion" -> "Conversion"', 'PREDICTIVE_038', ['regression', 'onboarding']),
    ('Correlation (Pearson): r=0.45 between "NPS" and "Revenue"', 'DATA_SCI_039', ['correlation', 'business-impact']),
    ('Z-score for participant 45: 2.4 (Outlier detected)', 'DATA_CLEAN_040', ['stats', 'outliers']),
    ('Average revenue per user (ARPU): $25.50', 'FINANCE_041', ['arpu', 'finance']),
    ('UMUX (Usability Metric for User Experience) total: 74.2', 'METRIC_LAB_042', ['umux', 'usability']),
    ('Single Ease Question (SEQ) variance: 2.1', 'STATS_LAB_043', ['seq', 'variance']),
    ('Task Success: 8/10 participants (80%)', 'MODERATED_STUDY_044', ['usability', 'success-rate']),
    ('First Click Test: 65% clicked "Settings" (Optimal path: "Profile")', 'TREEJACK_045', ['findability', 'navigation']),
    ('Misclick rate on "Confirm Order": 5.4%', 'MAZE_TEST_046', ['usability', 'error-rate']),
    ('Scroll depth (Average): 45% on Landing Page', 'HEATMAP_047', ['engagement', 'scroll-depth']),
    ('Average Rating (1-5): 4.2 (SD: 0.5)', 'APP_STORE_048', ['rating', 'satisfaction']),
    ('Bounce rate for Google Ads traffic: 62%', 'CAMPAIGN_049', ['bounce-rate', 'marketing']),
    ('Average session duration: 4m 12s', 'GA4_PRO_050', ['engagement', 'sessions']),
    ('Kaplan-Meier survival probability at 12 months: 0.35', 'CHURN_MOD_051', ['survival-analysis', 'retention']),
    ('Wilcoxon signed-rank test: W=45, p=0.03', 'NON_PARAM_052', ['stats', 'hypothesis-testing']),
    ('Kruskal-Wallis H test result: p=0.001', 'MULTI_GROUP_053', ['stats', 'anova-alt']),
    ('Mann-Whitney U test for Mobile vs Desktop usability: p=0.045', 'COMPARE_054', ['stats', 'platform-comparison']),
    ('Chi-square (X2) test for gender distribution: p=0.45', 'DEMO_ANALYSIS_055', ['stats', 'demographics']),
    ('Effect Size (Cohen\'s d): 0.85 (Large effect)', 'IMPACT_056', ['stats', 'effect-size']),
    ('Cronbach\'s Alpha: 0.91 for "User Trust" subscale', 'PSYCH_MODEL_057', ['reliability', 'stats']),
    ('Exploratory Factor Analysis (EFA) factor 1 explains 45% of variance', 'MODEL_EXP_058', ['factor-analysis', 'stats']),
    ('RMSE (Root Mean Square Error): 0.12 for price prediction model', 'ML_EVAL_059', ['stats', 'prediction']),
    ('Spearman\'s Rho: 0.56 (correlation between Rank and Satisfaction)', 'ORDINAL_060', ['stats', 'correlation']),
    ('Odds Ratio: 3.5 for users who see the "Discount" banner', 'A_B_STATS_061', ['stats', 'conversion']),
    ('Relative Risk (RR): 0.85 for new UI reducing errors', 'SAFETY_AUDIT_062', ['stats', 'safety']),
    ('Cohen\'s Kappa: 0.72 (Substantial inter-rater agreement)', 'CONTENT_ANALYSIS_063', ['kappa', 'reliability']),
    ('Standard Error (SE): 1.25 for mean completion time', 'STATS_DESK_064', ['stats', 'error']),
    ('99% Confidence Interval: [45.2, 58.4]', 'PRECISION_065', ['stats', 'ci']),
    ('Power (1-Beta): 0.82 (Target met for study)', 'POWER_CALC_066', ['stats', 'power']),
    ('Skewness: -1.2 (Left-skewed distribution of ratings)', 'DIST_ANALYSIS_067', ['stats', 'distribution']),
    ('Kurtosis: 3.5 (Leptokurtic distribution)', 'PEAK_ANALYSIS_068', ['stats', 'distribution']),
    ('GSR (Galvanic Skin Response) peak: 4.2uS during checkout error', 'PHYSIO_UX_069', ['biometrics', 'arousal']),
    ('Heart Rate Variability (HRV) decrease: 12% during high stress task', 'STRESS_RES_070', ['biometrics', 'cognitive-load']),
    ('Average Saccade Length: 3.2 degrees', 'EYE_MOVE_071', ['eye-tracking', 'hci']),
    ('Blink rate: 12 blinks/min (indicating high concentration)', 'ATTENTION_LAB_072', ['biometrics', 'concentration']),
    ('Heatmap "Hot Spot" coordinates: [450, 320] (Submit Button)', 'VISUAL_073', ['eye-tracking', 'heatmap']),
    ('First fixation time: 1.2s on Logo', 'BRAND_AWARE_074', ['eye-tracking', 'branding']),
    ('Total fixation duration: 4.5s on Pricing Table', 'EVAL_STUDY_075', ['eye-tracking', 'pricing']),
    ('Visit count: 1,240,500 (MTD)', 'TRAFFIC_076', ['analytics', 'scale']),
    ('Mobile traffic share: 68%', 'DEVICE_SPLIT_077', ['analytics', 'mobile']),
    ('Android vs iOS conversion: 2.5% vs 3.2%', 'PLATFORM_DATA_078', ['analytics', 'conversion']),
    ('DAU/MAU Ratio: 0.42 (Sticky product)', 'STICKINESS_079', ['analytics', 'engagement']),
    ('Average Revenue Per Paying User (ARPPU): $45.00', 'MONETIZATION_080', ['business', 'finance']),
    ('Free to Paid conversion rate: 4.5%', 'FUNNEL_081', ['conversion', 'business']),
    ('Organic vs Paid traffic ratio: 3:1', 'SEO_STATS_082', ['marketing', 'traffic']),
    ('Keyword "UX Research" ranking: #3', 'SERP_REPORT_083', ['seo', 'marketing']),
    ('Ad Spend (Total): $12,000 (CPC: $0.85)', 'AD_OPS_084', ['marketing', 'finance']),
    ('ROAS (Return on Ad Spend): 4.5x', 'ROI_ANALYSIS_085', ['marketing', 'roi']),
    ('NPS Detractors primary reason: "Pricing" (65%)', 'QUAL_QUANT_086', ['nps', 'feedback']),
    ('Likert scale mean (Ease of Use): 4.5/5', 'SURVEY_Q1_087', ['likert', 'satisfaction']),
    ('Likert scale median (Support Quality): 4.0', 'SURVEY_Q2_088', ['likert', 'satisfaction']),
    ('Net Easy Score: 62% (Easy - Difficult)', 'EASE_INDEX_089', ['metrics', 'usability']),
    ('Product Market Fit (PMF) score: 42% (Users who would be "very disappointed" without it)', 'STARTUP_METRIC_090', ['pmf', 'strategy']),
    ('Customer Effort Score (CES): 2.4 (Lower is better)', 'SUPPORT_STATS_091', ['ces', 'support']),
    ('Time to Value (TTV): 12m for new users', 'ONBOARD_092', ['onboarding', 'activation']),
    ('Activation rate: 35% (Users reaching milestone "A")', 'ACTIVATION_093', ['growth', 'product']),
    ('Referral rate: 1.2% (K-factor: 0.15)', 'VIRAL_LOOP_094', ['growth', 'marketing']),
    ('Average tickets per user: 0.45/month', 'CS_LOGS_095', ['support', 'reliability']),
    ('FCR (First Contact Resolution): 72%', 'CS_OPS_096', ['support', 'efficiency']),
    ('AHT (Average Handle Time): 8m 45s', 'CS_AGENT_097', ['support', 'efficiency']),
    ('NPS for "Premium" tier: +55', 'SEGMENT_NPS_098', ['nps', 'tiers']),
    ('Market share (Global): 12.4%', 'SHARE_REPORT_099', ['strategy', 'market']),
    ('Competitor B pricing delta: -15%', 'COMP_INTEL_100', ['pricing', 'strategy']),
    ('Overall Equipment Effectiveness (OEE): 78%', 'FACTORY_IOT_101', ['industrial', 'efficiency']),
    ('Downtime duration (Total): 14.5h this month', 'OPERATIONS_102', ['industrial', 'reliability']),
    ('Yield rate: 98.4%', 'PRODUCTION_103', ['industrial', 'quality']),
    ('Cycle time (Average): 12.5s per unit', 'PROCESS_LOG_104', ['industrial', 'speed']),
    ('Predictive maintenance alert accuracy: 92%', 'AI_MOD_105', ['ai', 'maintenance']),
    ('Energy consumption per unit: 4.2kWh', 'UTILITY_LOG_106', ['sustainability', 'energy']),
    ('Carbon footprint (Total): 1,240 tonnes CO2e', 'ESG_REPORT_107', ['sustainability', 'esg']),
    ('Employee satisfaction (eNPS): +12', 'HR_ANALYTICS_108', ['internal', 'loyalty']),
    ('Training completion rate: 95%', 'L_D_REPORT_109', ['internal', 'compliance']),
    ('Safety incidents (Total): 2 (MTD)', 'HSE_LOG_110', ['safety', 'compliance']),
    ('Bug density: 0.45 per KLOC', 'QA_METRICS_111', ['software', 'quality']),
    ('Technical debt ratio: 15%', 'TECH_OPS_112', ['software', 'maintenance']),
    ('Code coverage: 82%', 'CI_CD_LOG_113', ['software', 'quality']),
    ('Deployment frequency: 4.5/day', 'DEVOPS_114', ['software', 'agility']),
    ('MTTR (Mean Time to Repair): 2.4h', 'INCIDENT_LOG_115', ['software', 'reliability']),
    ('Uptime (SLA): 99.98%', 'SYSTEM_STATS_116', ['software', 'reliability']),
    ('API latency (P99): 120ms', 'PERF_DASH_117', ['software', 'performance']),
    ('Error rate (HTTP 5xx): 0.02%', 'ERROR_LOG_118', ['software', 'reliability']),
    ('Database query time (Avg): 15ms', 'DBA_REPORT_119', ['software', 'performance']),
    ('Cloud spend (AWS): $45,000/month', 'FINOPS_120', ['software', 'costs']),
    ('Search relevance score (NDCG): 0.85', 'SEARCH_AI_121', ['ai', 'search']),
    ('LLM token cost (Total): $1,200', 'AI_OPS_122', ['ai', 'costs']),
    ('Hallucination rate (Detected): 2.4%', 'AI_QA_123', ['ai', 'quality']),
    ('Recommendation click-through: 12.5%', 'RECO_ENGINE_124', ['ai', 'engagement']),
    ('Data freshness (Avg): 4.5m', 'DATA_PIPE_125', ['data', 'quality']),
    ('Schema drift alerts: 2 this week', 'DATA_GOV_126', ['data', 'quality']),
    ('Privacy request volume (GDPR): 142', 'LEGAL_OPS_127', ['legal', 'privacy']),
    ('Contract review time (Avg): 2.5 days', 'LEGAL_TECH_128', ['legal', 'efficiency']),
    ('Compliance audit score: 98/100', 'AUDIT_LOG_129', ['legal', 'compliance']),
    ('Risk exposure (Total): $1.2M', 'RISK_MGMT_130', ['strategy', 'risk']),
    ('Inventory turnover ratio: 4.5', 'SUPPLY_CHAIN_131', ['logistics', 'finance']),
    ('Order accuracy: 99.2%', 'WAREHOUSE_132', ['logistics', 'quality']),
    ('Shipping cost per order (Avg): $8.45', 'LOG_FINANCE_133', ['logistics', 'costs']),
    ('Last mile delivery success: 98.5%', 'DELIVERY_LOG_134', ['logistics', 'quality']),
    ('Supplier lead time (Mean): 14 days', 'PROCURE_135', ['logistics', 'timeline']),
    ('Customer Acquisition Cost (CAC): $125', 'MARKETING_KPI_136', ['business', 'marketing']),
    ('Payback period: 4.5 months', 'FIN_MODEL_137', ['business', 'finance']),
    ('EBITDA margin: 22%', 'ANNUAL_REP_138', ['business', 'finance']),
    ('Burn rate (Monthly): $450,000', 'STARTUP_BURN_139', ['business', 'finance']),
    ('Runway (Estimated): 14 months', 'STARTUP_RUN_140', ['business', 'finance']),
    ('Cap table dilution (Round B): 12%', 'VENTURE_141', ['business', 'finance']),
    ('ARR (Annual Recurring Revenue): $12.4M', 'SaaS_DASH_142', ['business', 'finance']),
    ('NRR (Net Revenue Retention): 112%', 'SaaS_RETAIN_143', ['business', 'retention']),
    ('GRR (Gross Revenue Retention): 92%', 'SaaS_CHURN_144', ['business', 'churn']),
    ('Quick Ratio: 1.45', 'FIN_ANALYSIS_145', ['business', 'finance']),
    ('Current Ratio: 2.1', 'BALANCE_SHEET_146', ['business', 'finance']),
    ('Debt-to-Equity: 0.45', 'CREDIT_REPORT_147', ['business', 'finance']),
    ('Interest coverage ratio: 12.4', 'SOLVENCY_148', ['business', 'finance']),
    ('Inventory days on hand: 42', 'RETAIL_FIN_149', ['business', 'logistics']),
    ('Accounts receivable days: 30', 'CASH_FLOW_150', ['business', 'finance']),
    ('Conversion rate by source (SEO): 3.2%', 'MKT_ATTRIBUTION_151', ['marketing', 'seo']),
    ('Conversion rate by source (PPC): 4.5%', 'MKT_ATTRIBUTION_152', ['marketing', 'ppc']),
    ('Conversion rate by source (Social): 1.8%', 'MKT_ATTRIBUTION_153', ['marketing', 'social']),
    ('Conversion rate by source (Direct): 5.2%', 'MKT_ATTRIBUTION_154', ['marketing', 'direct']),
    ('Cost per lead (CPL): $45.00', 'LEAD_GEN_155', ['marketing', 'costs']),
    ('Lead to MQL conversion: 25%', 'SALES_FUNNEL_156', ['marketing', 'sales']),
    ('MQL to SQL conversion: 15%', 'SALES_FUNNEL_157', ['marketing', 'sales']),
    ('SQL to Close conversion: 22%', 'SALES_FUNNEL_158', ['marketing', 'sales']),
    ('Sales cycle length (Avg): 120 days', 'CRM_DATA_159', ['sales', 'timeline']),
    ('Average deal size: $45,000', 'SALES_KPI_160', ['sales', 'finance']),
    ('Quota attainment (Team): 85%', 'SALES_OPS_161', ['sales', 'performance']),
    ('Pipeline coverage: 3.5x', 'FORECAST_162', ['sales', 'strategy']),
    ('Win rate (Competitive): 42%', 'WIN_LOSS_163', ['sales', 'competitive']),
    ('Loss rate (No Decision): 25%', 'WIN_LOSS_164', ['sales', 'strategy']),
    ('Churn risk score (Account X): 85/100', 'CS_HEALTH_165', ['cs', 'retention']),
    ('Expansion revenue (Monthly): $125,000', 'GROWTH_DASH_166', ['cs', 'revenue']),
    ('Contraction revenue (Monthly): $15,000', 'CHURN_DASH_167', ['cs', 'revenue']),
    ('Logo churn rate: 1.2%/month', 'RETAIN_REP_168', ['cs', 'churn']),
    ('Net Dollar Retention (NDR): 124%', 'RETAIN_REP_169', ['cs', 'retention']),
    ('Support CSAT: 4.8/5', 'SUPPORT_FEEDBACK_170', ['support', 'satisfaction']),
    ('First response time (FRT): 45m', 'SUPPORT_SLA_171', ['support', 'speed']),
    ('Resolution time (MTTR): 4.2h', 'SUPPORT_SLA_172', ['support', 'efficiency']),
    ('Backlog size: 142 tickets', 'SUPPORT_OPS_173', ['support', 'load']),
    ('Tier 1 to Tier 2 escalation: 12%', 'SUPPORT_OPS_174', ['support', 'complexity']),
    ('Knowledge base helpfulness: 82%', 'SELF_SERVICE_175', ['support', 'self-service']),
    ('Deflection rate: 25%', 'SELF_SERVICE_176', ['support', 'efficiency']),
    ('Chatbot success rate: 45%', 'AI_BOT_177', ['support', 'ai']),
    ('Live agent transfer rate: 55%', 'AI_BOT_178', ['support', 'ai']),
    ('Average order value (AOV): $85.50', 'ECOM_KPI_179', ['ecom', 'finance']),
    ('Units per transaction (UPT): 1.45', 'ECOM_KPI_180', ['ecom', 'finance']),
    ('Cart abandonment rate: 68%', 'CHECKOUT_KPI_181', ['ecom', 'usability']),
    ('Recovered cart rate: 12%', 'CHECKOUT_KPI_182', ['ecom', 'marketing']),
    ('Return rate: 8.4%', 'RETAIL_OPS_183', ['ecom', 'logistics']),
    ('Exchange rate (vs Return): 45%', 'RETAIL_OPS_184', ['ecom', 'loyalty']),
    ('SKU rationalization: 15% items removed', 'MERCHANDISE_185', ['ecom', 'strategy']),
    ('Gross Margin: 45%', 'ECOM_FIN_186', ['ecom', 'finance']),
    ('Contribution Margin: 22%', 'ECOM_FIN_187', ['ecom', 'finance']),
    ('Marketing efficiency ratio (MER): 4.5x', 'ECOM_MKT_188', ['ecom', 'marketing']),
    ('LTV/CAC ratio: 3.2x', 'UNIT_ECONOMICS_189', ['business', 'strategy']),
    ('Payback period (Months): 12', 'UNIT_ECONOMICS_190', ['business', 'strategy']),
    ('Contribution Margin (Unit): $12.45', 'UNIT_ECONOMICS_191', ['business', 'finance']),
    ('Variable cost per order: $4.50', 'UNIT_ECONOMICS_192', ['business', 'finance']),
    ('Fixed cost per order: $2.10', 'UNIT_ECONOMICS_193', ['business', 'finance']),
    ('Operating leverage: 2.5x', 'CORP_FIN_194', ['business', 'finance']),
    ('Free Cash Flow (FCF): $1.2M', 'CASH_REPORT_195', ['business', 'finance']),
    ('Working capital: $450,000', 'CASH_REPORT_196', ['business', 'finance']),
    ('Inventory valuation (FIFO): $1.2M', 'ASSET_REP_197', ['business', 'finance']),
    ('Asset turnover: 1.2', 'RATIO_ANALYSIS_198', ['business', 'finance']),
    ('Return on Assets (ROA): 12%', 'RATIO_ANALYSIS_199', ['business', 'finance']),
    ('Return on Equity (ROE): 22%', 'RATIO_ANALYSIS_200', ['business', 'finance']),
]
