#!/usr/bin/env python3
"""Fine-tune Gemma-4-E2B-it on Apple Silicon via PyTorch MPS.

This script is conservative for a Mac Studio M4 Max with 36 GB unified memory.
It uses the existing Hugging Face Alpaca-style UXR dataset plus the local
Istara SFT messages dataset generated by dataset-json-generator.py.
"""

import argparse
from pathlib import Path

import torch
from datasets import load_dataset, concatenate_datasets
from transformers import AutoModelForCausalLM, AutoTokenizer
from trl import SFTConfig, SFTTrainer
from peft import LoraConfig, TaskType

MODEL_ID = "google/gemma-4-E2B-it"
HUB_MODEL_ID = "henrique-simoes/gemma-4-e2b-istara-ux"
REPO_ID = "henrique-simoes/ux-research-strategy-dataset"
ROOT = Path(__file__).resolve().parent
DEFAULT_LOCAL_SFT = ROOT / "generated_datasets" / "istara_sft_messages.jsonl"
HUB_SFT_MESSAGES = f"hf://datasets/{REPO_ID}/istara_sft/istara_sft_messages.jsonl"

# Mac Studio M4 Max settings — conservative to avoid OOM
BATCH_SIZE = 1        # Keep at 1 for 36GB
GRAD_ACCUM = 32       # Effective batch = 32
MAX_LENGTH = 1024     # Shorter than ideal but fits memory


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--model-id", default=MODEL_ID)
    parser.add_argument("--hub-model-id", default=HUB_MODEL_ID)
    parser.add_argument("--output-dir", default=str(ROOT.parent / "LLMs" / "gemma-4-istara-ux"))
    parser.add_argument("--local-sft", type=Path, default=DEFAULT_LOCAL_SFT)
    parser.add_argument(
        "--use-hub-sft",
        action="store_true",
        help="Load istara_sft/istara_sft_messages.jsonl from the dataset repo instead of --local-sft.",
    )
    parser.add_argument("--push-to-hub", action="store_true")
    parser.add_argument("--epochs", type=float, default=3.0)
    parser.add_argument("--max-length", type=int, default=MAX_LENGTH)
    parser.add_argument("--batch-size", type=int, default=BATCH_SIZE)
    parser.add_argument("--grad-accum", type=int, default=GRAD_ACCUM)
    parser.add_argument("--learning-rate", type=float, default=2e-5)
    parser.add_argument("--smoke", action="store_true", help="Run a 2-step training smoke test.")
    return parser.parse_args()


def to_messages(ex):
    return {"messages": [
        {"role": "user", "content": ex["instruction"]},
        {"role": "assistant", "content": ex["response"]}
    ]}


def only_messages(ex):
    return {"messages": ex["messages"]}


def load_training_dataset(args: argparse.Namespace):
    print("[1/4] Loading datasets...")
    ux_raw = load_dataset(REPO_ID, data_files="data.parquet", split="train")
    ux = ux_raw.map(to_messages, remove_columns=ux_raw.column_names)

    if args.use_hub_sft:
        istara_raw = load_dataset("json", data_files=HUB_SFT_MESSAGES, split="train")
    else:
        if not args.local_sft.exists():
            raise FileNotFoundError(f"Local SFT dataset not found: {args.local_sft}")
        istara_raw = load_dataset("json", data_files=str(args.local_sft), split="train")

    istara = istara_raw.map(only_messages, remove_columns=istara_raw.column_names)
    dataset = concatenate_datasets([ux, istara]).shuffle(seed=42)

    if args.smoke:
        dataset = dataset.select(range(min(16, len(dataset))))

    print(f"  Base UXR examples: {len(ux)}")
    print(f"  Istara SFT examples: {len(istara)}")
    print(f"  Training examples: {len(dataset)}")
    return dataset


def main() -> int:
    args = parse_args()
    if not torch.backends.mps.is_available():
        raise RuntimeError("PyTorch MPS is not available on this machine.")

    dataset = load_training_dataset(args)

    print("[2/4] Loading model...")
    tokenizer = AutoTokenizer.from_pretrained(args.model_id, trust_remote_code=True)
    if tokenizer.pad_token is None:
        tokenizer.pad_token = tokenizer.eos_token

    model = AutoModelForCausalLM.from_pretrained(
        args.model_id,
        dtype=torch.float16,
        trust_remote_code=True,
    )
    model = model.to("mps")
    model.config.use_cache = False
    print(f"  {sum(p.numel() for p in model.parameters())/1e9:.1f}B params on MPS")

    print("[3/4] LoRA setup...")
    peft_config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=(
            r"model\.language_model\.layers\.\d+\."
            r"(self_attn\.(q_proj|k_proj|v_proj|o_proj)|mlp\.(gate_proj|up_proj|down_proj))$"
        ),
        lora_dropout=0.0,
        bias="none",
        task_type=TaskType.CAUSAL_LM,
    )

    print("[4/4] Training...")
    trainer = SFTTrainer(
        model=model,
        args=SFTConfig(
            output_dir=args.output_dir,
            num_train_epochs=args.epochs,
            max_steps=2 if args.smoke else -1,
            per_device_train_batch_size=args.batch_size,
            gradient_accumulation_steps=args.grad_accum,
            learning_rate=args.learning_rate,
            max_length=args.max_length,
            packing=False,
            fp16=False,
            bf16=False,
            gradient_checkpointing=True,
            logging_steps=1 if args.smoke else 10,
            logging_first_step=True,
            disable_tqdm=False,
            save_strategy="no" if args.smoke else "epoch",
            save_total_limit=2,
            push_to_hub=args.push_to_hub,
            hub_model_id=args.hub_model_id,
            seed=42,
            dataloader_num_workers=0,
            dataloader_pin_memory=False,
            report_to=[],
        ),
        train_dataset=dataset,
        processing_class=tokenizer,
        peft_config=peft_config,
    )

    trainer.train()
    if args.push_to_hub:
        trainer.push_to_hub()
        print(f"\nDone! https://huggingface.co/{args.hub_model_id}")
    else:
        print(f"\nDone! Local adapter saved under {args.output_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
