#!/usr/bin/env python3
"""Export Istara design tokens to W3C DTCG JSON — deterministically.

Single export graph (interface-design authority model):
    frontend/src/app/globals.css  --ui-* vars   -> semantic tokens (light+dark)
    frontend/tailwind.config.js   istara palette -> primitive tokens

Run with --check in CI/tests: fails if docs/design/tokens.json is not exactly
what the current sources produce. Never hand-edit tokens.json.
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
GLOBALS_CSS = ROOT / "frontend" / "src" / "app" / "globals.css"
TAILWIND_CONFIG = ROOT / "frontend" / "tailwind.config.js"
OUT_FILE = ROOT / "docs" / "design" / "tokens.json"

SEMANTIC_TOKENS = [
    "--ui-surface",
    "--ui-surface-raised",
    "--ui-surface-soft",
    "--ui-ink",
    "--ui-ink-muted",
    "--ui-ink-subtle",
    "--ui-rule",
    "--ui-rule-strong",
    "--ui-accent",
    "--ui-accent-soft",
    "--ui-focus",
    "--ui-danger",
    "--ui-warning",
    "--ui-success",
]
NON_COLOR = {
    "--ui-control-height": "dimension",
    "--ui-radius-panel": "dimension",
    "--ui-radius-control": "dimension",
    "--ui-radius-pill": "dimension",
}


def parse_css_vars(block: str) -> dict[str, str]:
    return dict(re.findall(r"(--[\w-]+):\s*([^;]+);", block))


def light_dark_blocks(css: str) -> tuple[dict[str, str], dict[str, str]]:
    root = re.search(r":root\s*\{(.*?)\}", css, re.DOTALL).group(1)  # type: ignore[union-attr]
    dark = re.search(r"\.dark\s*\{(.*?)\}", css, re.DOTALL).group(1)  # type: ignore[union-attr]
    return parse_css_vars(root), parse_css_vars(dark)


def istara_primitives() -> dict[str, str]:
    text = TAILWIND_CONFIG.read_text(encoding="utf-8")
    match = re.search(r"istara:\s*\{(.*?)\}", text, re.DOTALL)
    if not match:
        raise SystemExit("istara palette missing from tailwind.config.js")
    return {
        shade: hex_value.lower()
        for shade, hex_value in re.findall(
            r"(\d+):\s*\"(#[0-9a-fA-F]{6})\"", match.group(1)
        )
    }


def build() -> dict:
    css = GLOBALS_CSS.read_text(encoding="utf-8")
    light, dark = light_dark_blocks(css)
    primitives = istara_primitives()

    def color(value: str) -> dict:
        value = value.strip()
        if value.startswith("#"):
            return {"$type": "color", "$value": value}
        return {
            "$type": "color",
            "$value": value,
            "$extensions": {"source": "var-reference"},
        }

    def dimension(value: str) -> dict:
        return {"$type": "dimension", "$value": value.strip()}

    token = lambda v: color(v)  # noqa: E731

    semantic_light: dict[str, dict] = {}
    semantic_dark: dict[str, dict] = {}
    for name in SEMANTIC_TOKENS + list(NON_COLOR):
        factory = dimension if name in NON_COLOR else token
        if name in light:
            semantic_light[name.removeprefix("--ui-")] = factory(light[name])
        if name in dark:
            semantic_dark[name.removeprefix("--ui-")] = factory(dark[name])

    return {
        "$schema": "https://tr.designtokens.org/format/",
        "$description": "Istara design tokens. Generated by scripts/export_design_tokens.py — do not hand-edit. DESIGN.md is the authority.",
        "primitive": {
            "color": {
                "istara": {
                    f"{shade}": color(hex_value)
                    for shade, hex_value in sorted(
                        primitives.items(), key=lambda kv: int(kv[0])
                    )
                }
            }
        },
        "semantic": {
            "light": semantic_light,
            "dark": semantic_dark,
        },
    }


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="verify tokens.json matches sources; exit 1 on drift",
    )
    args = parser.parse_args()

    payload = json.dumps(build(), indent=2) + "\n"

    if args.check:
        current = OUT_FILE.read_text(encoding="utf-8") if OUT_FILE.exists() else ""
        if current != payload:
            print(
                "design tokens drifted: run `python scripts/export_design_tokens.py` and commit",
                file=sys.stderr,
            )
            return 1
        print(f"design tokens up to date: {OUT_FILE.relative_to(ROOT)}")
        return 0

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(payload, encoding="utf-8")
    print(f"wrote {OUT_FILE.relative_to(ROOT)} ({len(payload.splitlines())} lines)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
