#!/usr/bin/env python3
"""Auto-update the Capabilities Catalog section of AGENT.md.

Scans the codebase to generate an up-to-date capabilities catalog between
the <!-- CAPABILITIES_START --> and <!-- CAPABILITIES_END --> markers.

Run after adding any new feature:
    python scripts/update_agent_md.py
"""

import os
import re
import sys
from pathlib import Path

# Resolve project root
SCRIPT_DIR = Path(__file__).parent
PROJECT_ROOT = SCRIPT_DIR.parent
AGENT_MD = PROJECT_ROOT / "AGENT.md"
BACKEND = PROJECT_ROOT / "backend" / "app"
FRONTEND = PROJECT_ROOT / "frontend" / "src"
SKILLS_DIR = PROJECT_ROOT / "skills"

START_MARKER = "<!-- CAPABILITIES_START -->"
END_MARKER = "<!-- CAPABILITIES_END -->"


def scan_api_routes() -> list[str]:
    """Scan backend route files for API endpoint definitions."""
    routes_dir = BACKEND / "api" / "routes"
    endpoints = []
    if not routes_dir.exists():
        return endpoints
    for py_file in sorted(routes_dir.glob("*.py")):
        if py_file.name.startswith("_"):
            continue
        content = py_file.read_text()
        # Find router prefix
        prefix_match = re.search(r'prefix\s*=\s*["\']([^"\']+)["\']', content)
        prefix = prefix_match.group(1) if prefix_match else ""
        # Find endpoint decorators
        for match in re.finditer(r'@router\.(get|post|put|patch|delete)\s*\(\s*["\']([^"\']*)["\']', content):
            method = match.group(1).upper()
            path = match.group(2)
            full_path = f"/api{prefix}{path}" if not path.startswith("/api") else path
            endpoints.append(f"- `{method} {full_path}`")
    return endpoints


def scan_skills() -> dict[str, list[str]]:
    """Scan skill definitions organized by phase."""
    skills_by_phase: dict[str, list[str]] = {}
    if not SKILLS_DIR.exists():
        return skills_by_phase
    for phase_dir in sorted(SKILLS_DIR.iterdir()):
        if not phase_dir.is_dir():
            continue
        phase = phase_dir.name
        skills_by_phase[phase] = []
        for skill_dir in sorted(phase_dir.iterdir()):
            if not skill_dir.is_dir():
                continue
            skill_md = skill_dir / "SKILL.md"
            if skill_md.exists():
                content = skill_md.read_text()
                name_match = re.search(r'"display_name"\s*:\s*"([^"]+)"', content)
                name = name_match.group(1) if name_match else skill_dir.name.replace("-", " ").title()
                skills_by_phase[phase].append(name)
    return skills_by_phase


def scan_agents() -> list[str]:
    """Scan agent personas for names and roles."""
    personas_dir = BACKEND / "agents" / "personas"
    agents = []
    if not personas_dir.exists():
        return agents
    for agent_dir in sorted(personas_dir.iterdir()):
        if not agent_dir.is_dir() or agent_dir.name.startswith("."):
            continue
        # Skip UUID-named dirs (custom agents)
        if re.match(r"[0-9a-f]{8}-", agent_dir.name):
            continue
        core_md = agent_dir / "CORE.md"
        if core_md.exists():
            content = core_md.read_text()
            first_line = content.strip().split("\n")[0] if content.strip() else agent_dir.name
            agents.append(f"- **{agent_dir.name}**: {first_line.lstrip('# ')}")
    return agents


def scan_nav_items() -> list[str]:
    """Scan Sidebar.tsx for navigation items."""
    sidebar = FRONTEND / "components" / "layout" / "Sidebar.tsx"
    items = []
    if not sidebar.exists():
        return items
    content = sidebar.read_text()
    for match in re.finditer(r'label:\s*"([^"]+)"', content):
        items.append(match.group(1))
    return items


def scan_models() -> list[str]:
    """Scan database models."""
    models_dir = BACKEND / "models"
    models = []
    if not models_dir.exists():
        return models
    for py_file in sorted(models_dir.glob("*.py")):
        if py_file.name.startswith("_") or py_file.name == "database.py":
            continue
        content = py_file.read_text()
        for match in re.finditer(r'class\s+(\w+)\(Base\)', content):
            models.append(match.group(1))
    return models


def scan_mcp_tools() -> list[str]:
    """Scan MCP server for exposed tools."""
    mcp_server = BACKEND / "mcp" / "server.py"
    tools = []
    if not mcp_server.exists():
        return tools
    content = mcp_server.read_text()
    for match in re.finditer(r'@mcp\.tool\(\)\s*\n\s*async\s+def\s+(\w+)', content):
        tools.append(match.group(1))
    return tools


def generate_catalog() -> str:
    """Generate the full capabilities catalog as Markdown."""
    lines = [
        START_MARKER,
        "<!-- Auto-generated by scripts/update_agent_md.py -- DO NOT EDIT MANUALLY -->",
        "<!-- Run: python scripts/update_agent_md.py to regenerate -->",
        "",
        "## Capabilities Catalog",
        "",
    ]

    # Navigation
    nav_items = scan_nav_items()
    if nav_items:
        lines.append("### Navigation Menu")
        lines.append(f"- {', '.join(nav_items)}")
        lines.append("")

    # Agents
    agents = scan_agents()
    if agents:
        lines.append("### Agents")
        lines.extend(agents)
        lines.append("")

    # Skills
    skills = scan_skills()
    if skills:
        lines.append("### Skills")
        for phase, skill_list in skills.items():
            if skill_list:
                lines.append(f"- **{phase.title()}**: {', '.join(skill_list)}")
        lines.append("")

    # Models
    models = scan_models()
    if models:
        lines.append("### Data Models")
        lines.append(f"- {', '.join(models)}")
        lines.append("")

    # MCP Tools
    mcp_tools = scan_mcp_tools()
    if mcp_tools:
        lines.append("### MCP Server Tools")
        for tool in mcp_tools:
            lines.append(f"- `{tool}()`")
        lines.append("")

    # API Endpoints
    endpoints = scan_api_routes()
    if endpoints:
        lines.append(f"### API Endpoints ({len(endpoints)} total)")
        lines.append(f"Run `python scripts/update_agent_md.py --verbose` for full list.")
        lines.append("")

    lines.append(END_MARKER)
    return "\n".join(lines)


def update_agent_md():
    """Update AGENT.md with the generated catalog."""
    if not AGENT_MD.exists():
        print(f"ERROR: {AGENT_MD} not found")
        sys.exit(1)

    content = AGENT_MD.read_text()
    start_idx = content.find(START_MARKER)
    end_idx = content.find(END_MARKER)

    if start_idx == -1 or end_idx == -1:
        print(f"ERROR: Markers not found in {AGENT_MD}")
        sys.exit(1)

    catalog = generate_catalog()
    new_content = content[:start_idx] + catalog + content[end_idx + len(END_MARKER):]
    AGENT_MD.write_text(new_content)
    print(f"Updated {AGENT_MD} capabilities catalog.")


if __name__ == "__main__":
    update_agent_md()
