"""Human-readable rendering for Istara-generated artifacts."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Any


def _title_from_filename(filename: str) -> str:
    stem = Path(filename).stem or "artifact"
    return stem.replace("_", " ").replace("-", " ").title()


def _format_value(value: Any) -> str:
    if value is None:
        return "—"
    if isinstance(value, bool):
        return "Yes" if value else "No"
    if isinstance(value, float):
        return f"{value:.2f}".rstrip("0").rstrip(".")
    if isinstance(value, (int, str)):
        return str(value)
    return json.dumps(value, ensure_ascii=False)


def _render_dict_table(data: dict[str, Any]) -> list[str]:
    rows = []
    for key, value in data.items():
        if isinstance(value, (dict, list)):
            continue
        rows.append(f"| {key.replace('_', ' ').title()} | {_format_value(value)} |")
    if not rows:
        return []
    return ["| Field | Value |", "|---|---|", *rows, ""]


def _render_list_of_dicts(title: str, items: list[dict[str, Any]]) -> list[str]:
    lines = [f"## {title.replace('_', ' ').title()}", ""]
    for index, item in enumerate(items, start=1):
        heading = (
            item.get("code")
            or item.get("response_id")
            or item.get("id")
            or item.get("title")
            or item.get("name")
            or f"Item {index}"
        )
        lines.extend([f"### {_format_value(heading)}", ""])
        simple_rows = _render_dict_table(item)
        if simple_rows:
            lines.extend(simple_rows)
        for key, value in item.items():
            if isinstance(value, list):
                lines.extend(_render_list(key, value, level=4))
            elif isinstance(value, dict):
                lines.extend([f"#### {key.replace('_', ' ').title()}", ""])
                lines.extend(_render_dict(value, level=4))
        lines.append("")
    return lines


def _render_list(title: str, items: list[Any], level: int = 2) -> list[str]:
    heading = "#" * level
    if not items:
        return [f"{heading} {title.replace('_', ' ').title()}", "", "No items.", ""]
    if all(isinstance(item, dict) for item in items):
        return (
            _render_list_of_dicts(title, items)
            if level == 2
            else [
                f"{heading} {title.replace('_', ' ').title()}",
                "",
                *[
                    line
                    for index, item in enumerate(items, start=1)
                    for line in [
                        f"{heading}# {item.get('code') or item.get('response_id') or item.get('id') or f'Item {index}'}",
                        "",
                        *_render_dict(item, level=level + 1),
                        "",
                    ]
                ],
            ]
        )
    return [
        f"{heading} {title.replace('_', ' ').title()}",
        "",
        *[f"- {_format_value(item)}" for item in items],
        "",
    ]


def _render_dict(data: dict[str, Any], level: int = 2) -> list[str]:
    lines: list[str] = []
    simple_rows = _render_dict_table(data)
    if simple_rows:
        lines.extend(simple_rows)
    for key, value in data.items():
        if isinstance(value, list):
            lines.extend(_render_list(key, value, level=level))
        elif isinstance(value, dict):
            heading = "#" * level
            lines.extend([f"{heading} {key.replace('_', ' ').title()}", ""])
            lines.extend(_render_dict(value, level=level + 1))
    return lines


def render_artifact_document(
    filename: str, content: str, skill_name: str | None = None
) -> dict[str, str]:
    """Return a researcher-readable document representation for an artifact.

    Machine-oriented JSON remains useful internally, but generated Documents should
    present the human-readable artifact by default.
    """
    title = _title_from_filename(filename)
    source_note = f"Generated by `{skill_name}`." if skill_name else "Generated by Istara."

    try:
        parsed = json.loads(content)
    except (json.JSONDecodeError, TypeError):
        if Path(filename).suffix.lower() == ".md":
            readable = content
            rendered_name = filename
        else:
            readable = f"# {title}\n\n{source_note}\n\n{content.strip()}\n"
            rendered_name = f"{Path(filename).stem or 'artifact'}.md"
        return {"title": title, "file_name": rendered_name, "file_type": ".md", "content": readable}

    lines = [f"# {title}", "", source_note, ""]
    if isinstance(parsed, dict):
        summary = parsed.get("summary") or parsed.get("executive_summary")
        if summary:
            lines.extend(["## Summary", "", str(summary), ""])
        lines.extend(_render_dict(parsed))
    elif isinstance(parsed, list):
        lines.extend(_render_list("Results", parsed))
    else:
        lines.append(_format_value(parsed))

    readable = "\n".join(lines).strip() + "\n"
    return {
        "title": title,
        "file_name": f"{Path(filename).stem or 'artifact'}.md",
        "file_type": ".md",
        "content": readable,
    }
